// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testdbinfo

import "github.com/aarondl/opt/null"

var Banners = Table[
	bannerColumns,
	bannerIndexes,
	bannerForeignKeys,
	bannerUniques,
	bannerChecks,
]{
	Schema: "",
	Name:   "banners",
	Columns: bannerColumns{
		ID: column{
			Name:      "id",
			DBType:    "int",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		State: column{
			Name:      "state",
			DBType:    "enum('BS_1','BS_2','BS_3','BS_4','BS_5','BS_6','BS_7','BS_8','BS_9')",
			Default:   "BS_1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Sort: column{
			Name:      "sort",
			DBType:    "int",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: bannerIndexes{
		IDBannersSort: index{
			Type: "BTREE",
			Name: "id_banners_sort",
			Columns: []indexColumn{
				{
					Name:         "sort",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IDBannersState: index{
			Type: "BTREE",
			Name: "id_banners_state",
			Columns: []indexColumn{
				{
					Name:         "state",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type bannerColumns struct {
	ID        column
	Name      column
	State     column
	Sort      column
	CreatedAt column
	UpdatedAt column
}

func (c bannerColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.State, c.Sort, c.CreatedAt, c.UpdatedAt,
	}
}

type bannerIndexes struct {
	IDBannersSort  index
	IDBannersState index
	PRIMARY        index
}

func (i bannerIndexes) AsSlice() []index {
	return []index{
		i.IDBannersSort, i.IDBannersState, i.PRIMARY,
	}
}

type bannerForeignKeys struct{}

func (f bannerForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type bannerUniques struct{}

func (u bannerUniques) AsSlice() []constraint {
	return []constraint{}
}

type bannerChecks struct{}

func (c bannerChecks) AsSlice() []check {
	return []check{}
}
