// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testdbinfo

import "github.com/aarondl/opt/null"

var OrganizationPlans = Table[
	organizationPlanColumns,
	organizationPlanIndexes,
	organizationPlanForeignKeys,
	organizationPlanUniques,
	organizationPlanChecks,
]{
	Schema: "",
	Name:   "organization_plans",
	Columns: organizationPlanColumns{
		ID: column{
			Name:      "id",
			DBType:    "int",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		OrganizationID: column{
			Name:      "organization_id",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OrganizationPlanBuyerID: column{
			Name:      "organization_plan_buyer_id",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Plan: column{
			Name:      "plan",
			DBType:    "enum('PL_1','PL_2','PL_3','PL_4','PL_5','PL_6','PL_7','PL_8','PL_9','PL_10','PL_11','PL_12','PL_13','PL_14','PL_15','PL_16','PL_17','PL_18','PL_19','PL_20','PL_21')",
			Default:   "PL_1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PaymentMethod: column{
			Name:      "payment_method",
			DBType:    "enum('PM_1','PM_2')",
			Default:   "PM_2",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StripeCustomer: column{
			Name:      "stripe_customer",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StripeSubscription: column{
			Name:      "stripe_subscription",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StripeCharge: column{
			Name:      "stripe_charge",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UnsubscribedReason: column{
			Name:      "unsubscribed_reason",
			DBType:    "varchar(2048)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UnsubscribedRequestedAt: column{
			Name:      "unsubscribed_requested_at",
			DBType:    "datetime(6)",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UnsubscribedActuallyAt: column{
			Name:      "unsubscribed_actually_at",
			DBType:    "datetime(6)",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IsPending: column{
			Name:      "is_pending",
			DBType:    "tinyint(1)",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsEnabled: column{
			Name:      "is_enabled",
			DBType:    "tinyint(1)",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ContractPrice: column{
			Name:      "contract_price",
			DBType:    "int",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ContractVersion: column{
			Name:      "contract_version",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ContractPeriod: column{
			Name:      "contract_period",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ContractUpdatedAt: column{
			Name:      "contract_updated_at",
			DBType:    "datetime(6)",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ContractStartedAt: column{
			Name:      "contract_started_at",
			DBType:    "datetime(6)",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ContractExpiredAt: column{
			Name:      "contract_expired_at",
			DBType:    "datetime(6)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: organizationPlanIndexes{
		IDOrganizationPlansIsEnabled: index{
			Type: "BTREE",
			Name: "id_organization_plans_is_enabled",
			Columns: []indexColumn{
				{
					Name:         "is_enabled",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IDOrganizationPlansIsPending: index{
			Type: "BTREE",
			Name: "id_organization_plans_is_pending",
			Columns: []indexColumn{
				{
					Name:         "is_pending",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IDOrganizationPlansOrganizationID: index{
			Type: "BTREE",
			Name: "id_organization_plans_organization_id",
			Columns: []indexColumn{
				{
					Name:         "organization_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IDOrganizationPlansOrganizationPlanBuyerID: index{
			Type: "BTREE",
			Name: "id_organization_plans_organization_plan_buyer_id",
			Columns: []indexColumn{
				{
					Name:         "organization_plan_buyer_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		UkOrganizationPlanOrganizationIDIsEnabled: index{
			Type: "BTREE",
			Name: "uk_organization_plan_organization_id_is_enabled",
			Columns: []indexColumn{
				{
					Name:         "organization_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "is_enabled",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: organizationPlanForeignKeys{
		FKOrganizationPlansOrganizationID: foreignKey{
			constraint: constraint{
				Name:    "fk_organization_plans_organization_id",
				Columns: []string{"organization_id"},
				Comment: "",
			},
			ForeignTable:   "organizations",
			ForeignColumns: []string{"id"},
		},
		FKOrganizationPlansOrganizationPlanBuyerID: foreignKey{
			constraint: constraint{
				Name:    "fk_organization_plans_organization_plan_buyer_id",
				Columns: []string{"organization_plan_buyer_id"},
				Comment: "",
			},
			ForeignTable:   "organization_plan_buyers",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: organizationPlanUniques{
		UkOrganizationPlanOrganizationIDIsEnabled: constraint{
			Name:    "uk_organization_plan_organization_id_is_enabled",
			Columns: []string{"organization_id", "is_enabled"},
			Comment: "",
		},
	},

	Comment: "",
}

type organizationPlanColumns struct {
	ID                      column
	OrganizationID          column
	OrganizationPlanBuyerID column
	Plan                    column
	PaymentMethod           column
	StripeCustomer          column
	StripeSubscription      column
	StripeCharge            column
	UnsubscribedReason      column
	UnsubscribedRequestedAt column
	UnsubscribedActuallyAt  column
	IsPending               column
	IsEnabled               column
	ContractPrice           column
	ContractVersion         column
	ContractPeriod          column
	ContractUpdatedAt       column
	ContractStartedAt       column
	ContractExpiredAt       column
	CreatedAt               column
	UpdatedAt               column
}

func (c organizationPlanColumns) AsSlice() []column {
	return []column{
		c.ID, c.OrganizationID, c.OrganizationPlanBuyerID, c.Plan, c.PaymentMethod, c.StripeCustomer, c.StripeSubscription, c.StripeCharge, c.UnsubscribedReason, c.UnsubscribedRequestedAt, c.UnsubscribedActuallyAt, c.IsPending, c.IsEnabled, c.ContractPrice, c.ContractVersion, c.ContractPeriod, c.ContractUpdatedAt, c.ContractStartedAt, c.ContractExpiredAt, c.CreatedAt, c.UpdatedAt,
	}
}

type organizationPlanIndexes struct {
	IDOrganizationPlansIsEnabled               index
	IDOrganizationPlansIsPending               index
	IDOrganizationPlansOrganizationID          index
	IDOrganizationPlansOrganizationPlanBuyerID index
	PRIMARY                                    index
	UkOrganizationPlanOrganizationIDIsEnabled  index
}

func (i organizationPlanIndexes) AsSlice() []index {
	return []index{
		i.IDOrganizationPlansIsEnabled, i.IDOrganizationPlansIsPending, i.IDOrganizationPlansOrganizationID, i.IDOrganizationPlansOrganizationPlanBuyerID, i.PRIMARY, i.UkOrganizationPlanOrganizationIDIsEnabled,
	}
}

type organizationPlanForeignKeys struct {
	FKOrganizationPlansOrganizationID          foreignKey
	FKOrganizationPlansOrganizationPlanBuyerID foreignKey
}

func (f organizationPlanForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKOrganizationPlansOrganizationID, f.FKOrganizationPlansOrganizationPlanBuyerID,
	}
}

type organizationPlanUniques struct {
	UkOrganizationPlanOrganizationIDIsEnabled constraint
}

func (u organizationPlanUniques) AsSlice() []constraint {
	return []constraint{
		u.UkOrganizationPlanOrganizationIDIsEnabled,
	}
}

type organizationPlanChecks struct{}

func (c organizationPlanChecks) AsSlice() []check {
	return []check{}
}
