// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testdbinfo

import "github.com/aarondl/opt/null"

var OrganizationPlanBuyers = Table[
	organizationPlanBuyerColumns,
	organizationPlanBuyerIndexes,
	organizationPlanBuyerForeignKeys,
	organizationPlanBuyerUniques,
	organizationPlanBuyerChecks,
]{
	Schema: "",
	Name:   "organization_plan_buyers",
	Columns: organizationPlanBuyerColumns{
		ID: column{
			Name:      "id",
			DBType:    "int",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		CompanyName: column{
			Name:      "company_name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PhoneNumber: column{
			Name:      "phone_number",
			DBType:    "varchar(128)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Representative: column{
			Name:      "representative",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserName: column{
			Name:      "user_name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Postcode: column{
			Name:      "postcode",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Address1: column{
			Name:      "address1",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Address2: column{
			Name:      "address2",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InvoicePostcode: column{
			Name:      "invoice_postcode",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InvoiceAddress1: column{
			Name:      "invoice_address1",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InvoiceAddress2: column{
			Name:      "invoice_address2",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InvoiceUserName: column{
			Name:      "invoice_user_name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InvoiceEmail: column{
			Name:      "invoice_email",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "use in contract",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: organizationPlanBuyerIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type organizationPlanBuyerColumns struct {
	ID              column
	CompanyName     column
	PhoneNumber     column
	Email           column
	Representative  column
	UserName        column
	Postcode        column
	Address1        column
	Address2        column
	InvoicePostcode column
	InvoiceAddress1 column
	InvoiceAddress2 column
	InvoiceUserName column
	InvoiceEmail    column
	CreatedAt       column
	UpdatedAt       column
}

func (c organizationPlanBuyerColumns) AsSlice() []column {
	return []column{
		c.ID, c.CompanyName, c.PhoneNumber, c.Email, c.Representative, c.UserName, c.Postcode, c.Address1, c.Address2, c.InvoicePostcode, c.InvoiceAddress1, c.InvoiceAddress2, c.InvoiceUserName, c.InvoiceEmail, c.CreatedAt, c.UpdatedAt,
	}
}

type organizationPlanBuyerIndexes struct {
	PRIMARY index
}

func (i organizationPlanBuyerIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type organizationPlanBuyerForeignKeys struct{}

func (f organizationPlanBuyerForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type organizationPlanBuyerUniques struct{}

func (u organizationPlanBuyerUniques) AsSlice() []constraint {
	return []constraint{}
}

type organizationPlanBuyerChecks struct{}

func (c organizationPlanBuyerChecks) AsSlice() []check {
	return []check{}
}
