// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testdbinfo

import "github.com/aarondl/opt/null"

var Organizations = Table[
	organizationColumns,
	organizationIndexes,
	organizationForeignKeys,
	organizationUniques,
	organizationChecks,
]{
	Schema: "",
	Name:   "organizations",
	Columns: organizationColumns{
		ID: column{
			Name:      "id",
			DBType:    "int",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Identifier: column{
			Name:      "identifier",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Role: column{
			Name:      "role",
			DBType:    "enum('RL_1','RL_2')",
			Default:   "RL_1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsAuthed: column{
			Name:      "is_authed",
			DBType:    "tinyint(1)",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsDeleted: column{
			Name:      "is_deleted",
			DBType:    "tinyint(1)",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeletedAt: column{
			Name:      "deleted_at",
			DBType:    "datetime(6)",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp(6)",
			Default:   "CURRENT_TIMESTAMP(6)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: organizationIndexes{
		IDOrganizationsIsAuthed: index{
			Type: "BTREE",
			Name: "id_organizations_is_authed",
			Columns: []indexColumn{
				{
					Name:         "is_authed",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IDOrganizationsIsDeleted: index{
			Type: "BTREE",
			Name: "id_organizations_is_deleted",
			Columns: []indexColumn{
				{
					Name:         "is_deleted",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IDOrganizationsRole: index{
			Type: "BTREE",
			Name: "id_organizations_role",
			Columns: []indexColumn{
				{
					Name:         "role",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		UkOrganizationsIdentifier: index{
			Type: "BTREE",
			Name: "uk_organizations_identifier",
			Columns: []indexColumn{
				{
					Name:         "identifier",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: organizationUniques{
		UkOrganizationsIdentifier: constraint{
			Name:    "uk_organizations_identifier",
			Columns: []string{"identifier"},
			Comment: "",
		},
	},

	Comment: "",
}

type organizationColumns struct {
	ID         column
	Identifier column
	Role       column
	IsAuthed   column
	IsDeleted  column
	DeletedAt  column
	CreatedAt  column
	UpdatedAt  column
}

func (c organizationColumns) AsSlice() []column {
	return []column{
		c.ID, c.Identifier, c.Role, c.IsAuthed, c.IsDeleted, c.DeletedAt, c.CreatedAt, c.UpdatedAt,
	}
}

type organizationIndexes struct {
	IDOrganizationsIsAuthed   index
	IDOrganizationsIsDeleted  index
	IDOrganizationsRole       index
	PRIMARY                   index
	UkOrganizationsIdentifier index
}

func (i organizationIndexes) AsSlice() []index {
	return []index{
		i.IDOrganizationsIsAuthed, i.IDOrganizationsIsDeleted, i.IDOrganizationsRole, i.PRIMARY, i.UkOrganizationsIdentifier,
	}
}

type organizationForeignKeys struct{}

func (f organizationForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type organizationUniques struct {
	UkOrganizationsIdentifier constraint
}

func (u organizationUniques) AsSlice() []constraint {
	return []constraint{
		u.UkOrganizationsIdentifier,
	}
}

type organizationChecks struct{}

func (c organizationChecks) AsSlice() []check {
	return []check{}
}
