// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testmodels

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	enums "github.com/eiicon-company/bobby/internal/testenums"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
)

// Banner is an object representing the database table.
type Banner struct {
	ID        int32              `db:"id,pk,autoincr" `
	Name      string             `db:"name" `
	State     enums.BannersState `db:"state" `
	Sort      int32              `db:"sort" `
	CreatedAt time.Time          `db:"created_at" `
	UpdatedAt time.Time          `db:"updated_at" `
}

// BannerSlice is an alias for a slice of pointers to Banner.
// This should almost always be used instead of []*Banner.
type BannerSlice []*Banner

// Banners contains methods to work with the banners table
var Banners = mysql.NewTablex[*Banner, BannerSlice, *BannerSetter]("banners", buildBannerColumns("banners"), []string{"id"})

// BannersQuery is a query on the banners table
type BannersQuery = *mysql.ViewQuery[*Banner, BannerSlice]

func buildBannerColumns(alias string) bannerColumns {
	return bannerColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "state", "sort", "created_at", "updated_at",
		).WithParent("banners"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		Name:       mysql.Quote(alias, "name"),
		State:      mysql.Quote(alias, "state"),
		Sort:       mysql.Quote(alias, "sort"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type bannerColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	Name       mysql.Expression
	State      mysql.Expression
	Sort       mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c bannerColumns) Alias() string {
	return c.tableAlias
}

func (bannerColumns) AliasedAs(alias string) bannerColumns {
	return buildBannerColumns(alias)
}

// BannerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type BannerSetter struct {
	ID        omit.Val[int32]              `db:"id,pk,autoincr" `
	Name      omit.Val[string]             `db:"name" `
	State     omit.Val[enums.BannersState] `db:"state" `
	Sort      omit.Val[int32]              `db:"sort" `
	CreatedAt omit.Val[time.Time]          `db:"created_at" `
	UpdatedAt omit.Val[time.Time]          `db:"updated_at" `
}

func (s BannerSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.State.IsValue() {
		vals = append(vals, "state")
	}
	if s.Sort.IsValue() {
		vals = append(vals, "sort")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s BannerSetter) Overwrite(t *Banner) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.State.IsValue() {
		t.State = s.State.MustGet()
	}
	if s.Sort.IsValue() {
		t.Sort = s.Sort.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *BannerSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Banners.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.State.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.State.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Sort.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Sort.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s BannerSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("banners")...)
}

func (s BannerSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.State.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "state")...),
			mysql.Arg(s.State),
		}})
	}

	if s.Sort.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "sort")...),
			mysql.Arg(s.Sort),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindBanner retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindBanner(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*Banner, error) {
	if len(cols) == 0 {
		return Banners.Query(
			sm.Where(Banners.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Banners.Query(
		sm.Where(Banners.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Banners.Columns.Only(cols...)),
	).One(ctx, exec)
}

// BannerExists checks the presence of a single record by primary key
func BannerExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return Banners.Query(
		sm.Where(Banners.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Banner is retrieved from the database
func (o *Banner) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Banners.AfterSelectHooks.RunHooks(ctx, exec, BannerSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Banners.AfterInsertHooks.RunHooks(ctx, exec, BannerSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Banners.AfterUpdateHooks.RunHooks(ctx, exec, BannerSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Banners.AfterDeleteHooks.RunHooks(ctx, exec, BannerSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Banner
func (o *Banner) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Banner) pkEQ() dialect.Expression {
	return mysql.Quote("banners", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Banner
func (o *Banner) Update(ctx context.Context, exec bob.Executor, s *BannerSetter) error {
	_, err := Banners.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Banner record with an executor
func (o *Banner) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Banners.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Banner using the executor
func (o *Banner) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Banners.Query(
		sm.Where(Banners.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after BannerSlice is retrieved from the database
func (o BannerSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Banners.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Banners.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Banners.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Banners.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o BannerSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("banners", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o BannerSlice) copyMatchingRows(from ...*Banner) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o BannerSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Banners.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Banner:
				o.copyMatchingRows(retrieved)
			case []*Banner:
				o.copyMatchingRows(retrieved...)
			case BannerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Banner or a slice of Banner
				// then run the AfterUpdateHooks on the slice
				_, err = Banners.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o BannerSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Banners.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Banner:
				o.copyMatchingRows(retrieved)
			case []*Banner:
				o.copyMatchingRows(retrieved...)
			case BannerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Banner or a slice of Banner
				// then run the AfterDeleteHooks on the slice
				_, err = Banners.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o BannerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals BannerSetter) error {
	_, err := Banners.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o BannerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Banners.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o BannerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Banners.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type bannerWhere[Q mysql.Filterable] struct {
	ID        mysql.WhereMod[Q, int32]
	Name      mysql.WhereMod[Q, string]
	State     mysql.WhereMod[Q, enums.BannersState]
	Sort      mysql.WhereMod[Q, int32]
	CreatedAt mysql.WhereMod[Q, time.Time]
	UpdatedAt mysql.WhereMod[Q, time.Time]
}

func (bannerWhere[Q]) AliasedAs(alias string) bannerWhere[Q] {
	return buildBannerWhere[Q](buildBannerColumns(alias))
}

func buildBannerWhere[Q mysql.Filterable](cols bannerColumns) bannerWhere[Q] {
	return bannerWhere[Q]{
		ID:        mysql.Where[Q, int32](cols.ID),
		Name:      mysql.Where[Q, string](cols.Name),
		State:     mysql.Where[Q, enums.BannersState](cols.State),
		Sort:      mysql.Where[Q, int32](cols.Sort),
		CreatedAt: mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}
