// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testmodels

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q mysql.Filterable]() struct {
	Banners                bannerWhere[Q]
	OrganizationPlanBuyers organizationPlanBuyerWhere[Q]
	OrganizationPlans      organizationPlanWhere[Q]
	Organizations          organizationWhere[Q]
} {
	return struct {
		Banners                bannerWhere[Q]
		OrganizationPlanBuyers organizationPlanBuyerWhere[Q]
		OrganizationPlans      organizationPlanWhere[Q]
		Organizations          organizationWhere[Q]
	}{
		Banners:                buildBannerWhere[Q](Banners.Columns),
		OrganizationPlanBuyers: buildOrganizationPlanBuyerWhere[Q](OrganizationPlanBuyers.Columns),
		OrganizationPlans:      buildOrganizationPlanWhere[Q](OrganizationPlans.Columns),
		Organizations:          buildOrganizationWhere[Q](Organizations.Columns),
	}
}
