// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testmodels

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	enums "github.com/eiicon-company/bobo/internal/testenums"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Organization is an object representing the database table.
type Organization struct {
	ID int32 `db:"id,pk,autoincr" `
	// use as like slug
	Identifier string `db:"identifier" `
	// Which is used by it
	Role enums.OrganizationsRole `db:"role" `
	// Authenticated by administrator
	IsAuthed  bool                `db:"is_authed" `
	IsDeleted bool                `db:"is_deleted" `
	DeletedAt null.Val[time.Time] `db:"deleted_at" `
	CreatedAt time.Time           `db:"created_at" `
	UpdatedAt time.Time           `db:"updated_at" `

	R organizationR `db:"-" `
}

// OrganizationSlice is an alias for a slice of pointers to Organization.
// This should almost always be used instead of []*Organization.
type OrganizationSlice []*Organization

// Organizations contains methods to work with the organizations table
var Organizations = mysql.NewTablex[*Organization, OrganizationSlice, *OrganizationSetter]("organizations", buildOrganizationColumns("organizations"), []string{"id"}, []string{"identifier"})

// OrganizationsQuery is a query on the organizations table
type OrganizationsQuery = *mysql.ViewQuery[*Organization, OrganizationSlice]

// organizationR is where relationships are stored.
type organizationR struct {
	OrganizationPlans OrganizationPlanSlice // fk_organization_plans_organization_id
}

func buildOrganizationColumns(alias string) organizationColumns {
	return organizationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "identifier", "role", "is_authed", "is_deleted", "deleted_at", "created_at", "updated_at",
		).WithParent("organizations"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		Identifier: mysql.Quote(alias, "identifier"),
		Role:       mysql.Quote(alias, "role"),
		IsAuthed:   mysql.Quote(alias, "is_authed"),
		IsDeleted:  mysql.Quote(alias, "is_deleted"),
		DeletedAt:  mysql.Quote(alias, "deleted_at"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type organizationColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	Identifier mysql.Expression
	Role       mysql.Expression
	IsAuthed   mysql.Expression
	IsDeleted  mysql.Expression
	DeletedAt  mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c organizationColumns) Alias() string {
	return c.tableAlias
}

func (organizationColumns) AliasedAs(alias string) organizationColumns {
	return buildOrganizationColumns(alias)
}

// OrganizationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrganizationSetter struct {
	ID         omit.Val[int32]                   `db:"id,pk,autoincr" `
	Identifier omit.Val[string]                  `db:"identifier" `
	Role       omit.Val[enums.OrganizationsRole] `db:"role" `
	IsAuthed   omit.Val[bool]                    `db:"is_authed" `
	IsDeleted  omit.Val[bool]                    `db:"is_deleted" `
	DeletedAt  omitnull.Val[time.Time]           `db:"deleted_at" `
	CreatedAt  omit.Val[time.Time]               `db:"created_at" `
	UpdatedAt  omit.Val[time.Time]               `db:"updated_at" `
}

func (s OrganizationSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Identifier.IsValue() {
		vals = append(vals, "identifier")
	}
	if s.Role.IsValue() {
		vals = append(vals, "role")
	}
	if s.IsAuthed.IsValue() {
		vals = append(vals, "is_authed")
	}
	if s.IsDeleted.IsValue() {
		vals = append(vals, "is_deleted")
	}
	if !s.DeletedAt.IsUnset() {
		vals = append(vals, "deleted_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrganizationSetter) Overwrite(t *Organization) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Identifier.IsValue() {
		t.Identifier = s.Identifier.MustGet()
	}
	if s.Role.IsValue() {
		t.Role = s.Role.MustGet()
	}
	if s.IsAuthed.IsValue() {
		t.IsAuthed = s.IsAuthed.MustGet()
	}
	if s.IsDeleted.IsValue() {
		t.IsDeleted = s.IsDeleted.MustGet()
	}
	if !s.DeletedAt.IsUnset() {
		t.DeletedAt = s.DeletedAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OrganizationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Organizations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Identifier.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Identifier.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Role.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Role.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsAuthed.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsAuthed.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsDeleted.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsDeleted.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.DeletedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.DeletedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s OrganizationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("organizations")...)
}

func (s OrganizationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Identifier.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "identifier")...),
			mysql.Arg(s.Identifier),
		}})
	}

	if s.Role.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "role")...),
			mysql.Arg(s.Role),
		}})
	}

	if s.IsAuthed.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_authed")...),
			mysql.Arg(s.IsAuthed),
		}})
	}

	if s.IsDeleted.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_deleted")...),
			mysql.Arg(s.IsDeleted),
		}})
	}

	if !s.DeletedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "deleted_at")...),
			mysql.Arg(s.DeletedAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrganization retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrganization(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*Organization, error) {
	if len(cols) == 0 {
		return Organizations.Query(
			sm.Where(Organizations.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Organizations.Query(
		sm.Where(Organizations.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Organizations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrganizationExists checks the presence of a single record by primary key
func OrganizationExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return Organizations.Query(
		sm.Where(Organizations.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Organization is retrieved from the database
func (o *Organization) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Organizations.AfterSelectHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Organizations.AfterInsertHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Organization
func (o *Organization) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Organization) pkEQ() dialect.Expression {
	return mysql.Quote("organizations", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Organization
func (o *Organization) Update(ctx context.Context, exec bob.Executor, s *OrganizationSetter) error {
	_, err := Organizations.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Organization record with an executor
func (o *Organization) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Organizations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Organization using the executor
func (o *Organization) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Organizations.Query(
		sm.Where(Organizations.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrganizationSlice is retrieved from the database
func (o OrganizationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Organizations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Organizations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrganizationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("organizations", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrganizationSlice) copyMatchingRows(from ...*Organization) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrganizationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Organizations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Organization:
				o.copyMatchingRows(retrieved)
			case []*Organization:
				o.copyMatchingRows(retrieved...)
			case OrganizationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Organization or a slice of Organization
				// then run the AfterUpdateHooks on the slice
				_, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrganizationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Organizations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Organization:
				o.copyMatchingRows(retrieved)
			case []*Organization:
				o.copyMatchingRows(retrieved...)
			case OrganizationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Organization or a slice of Organization
				// then run the AfterDeleteHooks on the slice
				_, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrganizationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrganizationSetter) error {
	_, err := Organizations.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o OrganizationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Organizations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrganizationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Organizations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// OrganizationPlans starts a query for related objects on organization_plans
func (o *Organization) OrganizationPlans(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPlansQuery {
	return OrganizationPlans.Query(append(mods,
		sm.Where(OrganizationPlans.Columns.OrganizationID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) OrganizationPlans(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPlansQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return OrganizationPlans.Query(append(mods,
		sm.Where(mysql.Group(OrganizationPlans.Columns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

func insertOrganizationOrganizationPlans0(ctx context.Context, exec bob.Executor, organizationPlans1 []*OrganizationPlanSetter, organization0 *Organization) (OrganizationPlanSlice, error) {
	for i := range organizationPlans1 {
		organizationPlans1[i].OrganizationID = omit.From(organization0.ID)
	}

	ret, err := OrganizationPlans.Insert(bob.ToMods(organizationPlans1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationOrganizationPlans0: %w", err)
	}

	return ret, nil
}

func attachOrganizationOrganizationPlans0(ctx context.Context, exec bob.Executor, count int, organizationPlans1 OrganizationPlanSlice, organization0 *Organization) (OrganizationPlanSlice, error) {
	setter := &OrganizationPlanSetter{
		OrganizationID: omit.From(organization0.ID),
	}

	err := organizationPlans1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationOrganizationPlans0: %w", err)
	}

	return organizationPlans1, nil
}

func (organization0 *Organization) InsertOrganizationPlans(ctx context.Context, exec bob.Executor, related ...*OrganizationPlanSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	organizationPlans1, err := insertOrganizationOrganizationPlans0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationPlans = append(organization0.R.OrganizationPlans, organizationPlans1...)

	for _, rel := range organizationPlans1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachOrganizationPlans(ctx context.Context, exec bob.Executor, related ...*OrganizationPlan) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	organizationPlans1 := OrganizationPlanSlice(related)

	_, err = attachOrganizationOrganizationPlans0(ctx, exec, len(related), organizationPlans1, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationPlans = append(organization0.R.OrganizationPlans, organizationPlans1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}

type organizationWhere[Q mysql.Filterable] struct {
	ID         mysql.WhereMod[Q, int32]
	Identifier mysql.WhereMod[Q, string]
	Role       mysql.WhereMod[Q, enums.OrganizationsRole]
	IsAuthed   mysql.WhereMod[Q, bool]
	IsDeleted  mysql.WhereMod[Q, bool]
	DeletedAt  mysql.WhereNullMod[Q, time.Time]
	CreatedAt  mysql.WhereMod[Q, time.Time]
	UpdatedAt  mysql.WhereMod[Q, time.Time]
}

func (organizationWhere[Q]) AliasedAs(alias string) organizationWhere[Q] {
	return buildOrganizationWhere[Q](buildOrganizationColumns(alias))
}

func buildOrganizationWhere[Q mysql.Filterable](cols organizationColumns) organizationWhere[Q] {
	return organizationWhere[Q]{
		ID:         mysql.Where[Q, int32](cols.ID),
		Identifier: mysql.Where[Q, string](cols.Identifier),
		Role:       mysql.Where[Q, enums.OrganizationsRole](cols.Role),
		IsAuthed:   mysql.Where[Q, bool](cols.IsAuthed),
		IsDeleted:  mysql.Where[Q, bool](cols.IsDeleted),
		DeletedAt:  mysql.WhereNull[Q, time.Time](cols.DeletedAt),
		CreatedAt:  mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:  mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Organization) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "OrganizationPlans":
		rels, ok := retrieved.(OrganizationPlanSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationPlans = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	default:
		return fmt.Errorf("organization has no relationship %q", name)
	}
}

type organizationPreloader struct{}

func buildOrganizationPreloader() organizationPreloader {
	return organizationPreloader{}
}

type organizationThenLoader[Q orm.Loadable] struct {
	OrganizationPlans func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrganizationThenLoader[Q orm.Loadable]() organizationThenLoader[Q] {
	type OrganizationPlansLoadInterface interface {
		LoadOrganizationPlans(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return organizationThenLoader[Q]{
		OrganizationPlans: thenLoadBuilder[Q](
			"OrganizationPlans",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationPlansLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationPlans(ctx, exec, mods...)
			},
		),
	}
}

// LoadOrganizationPlans loads the organization's OrganizationPlans into the .R struct
func (o *Organization) LoadOrganizationPlans(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationPlans = nil

	related, err := o.OrganizationPlans(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.OrganizationPlans = related
	return nil
}

// LoadOrganizationPlans loads the organization's OrganizationPlans into the .R struct
func (os OrganizationSlice) LoadOrganizationPlans(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationPlans, err := os.OrganizationPlans(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OrganizationPlans = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationPlans {

			if !(o.ID == rel.OrganizationID) {
				continue
			}

			rel.R.Organization = o

			o.R.OrganizationPlans = append(o.R.OrganizationPlans, rel)
		}
	}

	return nil
}

type organizationJoins[Q dialect.Joinable] struct {
	typ               string
	OrganizationPlans modAs[Q, organizationPlanColumns]
}

func (j organizationJoins[Q]) aliasedAs(alias string) organizationJoins[Q] {
	return buildOrganizationJoins[Q](buildOrganizationColumns(alias), j.typ)
}

func buildOrganizationJoins[Q dialect.Joinable](cols organizationColumns, typ string) organizationJoins[Q] {
	return organizationJoins[Q]{
		typ: typ,
		OrganizationPlans: modAs[Q, organizationPlanColumns]{
			c: OrganizationPlans.Columns,
			f: func(to organizationPlanColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationPlans.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
