// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testmodels

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	enums "github.com/eiicon-company/bobby/internal/testenums"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// OrganizationPlan is an object representing the database table.
type OrganizationPlan struct {
	ID                      int32                                `db:"id,pk,autoincr" `
	OrganizationID          int32                                `db:"organization_id" `
	OrganizationPlanBuyerID int32                                `db:"organization_plan_buyer_id" `
	Plan                    enums.OrganizationPlansPlan          `db:"plan" `
	PaymentMethod           enums.OrganizationPlansPaymentMethod `db:"payment_method" `
	StripeCustomer          string                               `db:"stripe_customer" `
	StripeSubscription      string                               `db:"stripe_subscription" `
	StripeCharge            string                               `db:"stripe_charge" `
	UnsubscribedReason      string                               `db:"unsubscribed_reason" `
	UnsubscribedRequestedAt null.Val[time.Time]                  `db:"unsubscribed_requested_at" `
	UnsubscribedActuallyAt  null.Val[time.Time]                  `db:"unsubscribed_actually_at" `
	IsPending               bool                                 `db:"is_pending" `
	IsEnabled               null.Val[bool]                       `db:"is_enabled" `
	ContractPrice           int32                                `db:"contract_price" `
	ContractVersion         int32                                `db:"contract_version" `
	ContractPeriod          int32                                `db:"contract_period" `
	ContractUpdatedAt       null.Val[time.Time]                  `db:"contract_updated_at" `
	ContractStartedAt       null.Val[time.Time]                  `db:"contract_started_at" `
	ContractExpiredAt       time.Time                            `db:"contract_expired_at" `
	CreatedAt               time.Time                            `db:"created_at" `
	UpdatedAt               time.Time                            `db:"updated_at" `

	R organizationPlanR `db:"-" `
}

// OrganizationPlanSlice is an alias for a slice of pointers to OrganizationPlan.
// This should almost always be used instead of []*OrganizationPlan.
type OrganizationPlanSlice []*OrganizationPlan

// OrganizationPlans contains methods to work with the organization_plans table
var OrganizationPlans = mysql.NewTablex[*OrganizationPlan, OrganizationPlanSlice, *OrganizationPlanSetter]("organization_plans", buildOrganizationPlanColumns("organization_plans"), []string{"id"}, []string{"organization_id", "is_enabled"})

// OrganizationPlansQuery is a query on the organization_plans table
type OrganizationPlansQuery = *mysql.ViewQuery[*OrganizationPlan, OrganizationPlanSlice]

// organizationPlanR is where relationships are stored.
type organizationPlanR struct {
	Organization          *Organization          // fk_organization_plans_organization_id
	OrganizationPlanBuyer *OrganizationPlanBuyer // fk_organization_plans_organization_plan_buyer_id
}

func buildOrganizationPlanColumns(alias string) organizationPlanColumns {
	return organizationPlanColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "organization_id", "organization_plan_buyer_id", "plan", "payment_method", "stripe_customer", "stripe_subscription", "stripe_charge", "unsubscribed_reason", "unsubscribed_requested_at", "unsubscribed_actually_at", "is_pending", "is_enabled", "contract_price", "contract_version", "contract_period", "contract_updated_at", "contract_started_at", "contract_expired_at", "created_at", "updated_at",
		).WithParent("organization_plans"),
		tableAlias:              alias,
		ID:                      mysql.Quote(alias, "id"),
		OrganizationID:          mysql.Quote(alias, "organization_id"),
		OrganizationPlanBuyerID: mysql.Quote(alias, "organization_plan_buyer_id"),
		Plan:                    mysql.Quote(alias, "plan"),
		PaymentMethod:           mysql.Quote(alias, "payment_method"),
		StripeCustomer:          mysql.Quote(alias, "stripe_customer"),
		StripeSubscription:      mysql.Quote(alias, "stripe_subscription"),
		StripeCharge:            mysql.Quote(alias, "stripe_charge"),
		UnsubscribedReason:      mysql.Quote(alias, "unsubscribed_reason"),
		UnsubscribedRequestedAt: mysql.Quote(alias, "unsubscribed_requested_at"),
		UnsubscribedActuallyAt:  mysql.Quote(alias, "unsubscribed_actually_at"),
		IsPending:               mysql.Quote(alias, "is_pending"),
		IsEnabled:               mysql.Quote(alias, "is_enabled"),
		ContractPrice:           mysql.Quote(alias, "contract_price"),
		ContractVersion:         mysql.Quote(alias, "contract_version"),
		ContractPeriod:          mysql.Quote(alias, "contract_period"),
		ContractUpdatedAt:       mysql.Quote(alias, "contract_updated_at"),
		ContractStartedAt:       mysql.Quote(alias, "contract_started_at"),
		ContractExpiredAt:       mysql.Quote(alias, "contract_expired_at"),
		CreatedAt:               mysql.Quote(alias, "created_at"),
		UpdatedAt:               mysql.Quote(alias, "updated_at"),
	}
}

type organizationPlanColumns struct {
	expr.ColumnsExpr
	tableAlias              string
	ID                      mysql.Expression
	OrganizationID          mysql.Expression
	OrganizationPlanBuyerID mysql.Expression
	Plan                    mysql.Expression
	PaymentMethod           mysql.Expression
	StripeCustomer          mysql.Expression
	StripeSubscription      mysql.Expression
	StripeCharge            mysql.Expression
	UnsubscribedReason      mysql.Expression
	UnsubscribedRequestedAt mysql.Expression
	UnsubscribedActuallyAt  mysql.Expression
	IsPending               mysql.Expression
	IsEnabled               mysql.Expression
	ContractPrice           mysql.Expression
	ContractVersion         mysql.Expression
	ContractPeriod          mysql.Expression
	ContractUpdatedAt       mysql.Expression
	ContractStartedAt       mysql.Expression
	ContractExpiredAt       mysql.Expression
	CreatedAt               mysql.Expression
	UpdatedAt               mysql.Expression
}

func (c organizationPlanColumns) Alias() string {
	return c.tableAlias
}

func (organizationPlanColumns) AliasedAs(alias string) organizationPlanColumns {
	return buildOrganizationPlanColumns(alias)
}

// OrganizationPlanSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrganizationPlanSetter struct {
	ID                      omit.Val[int32]                                `db:"id,pk,autoincr" `
	OrganizationID          omit.Val[int32]                                `db:"organization_id" `
	OrganizationPlanBuyerID omit.Val[int32]                                `db:"organization_plan_buyer_id" `
	Plan                    omit.Val[enums.OrganizationPlansPlan]          `db:"plan" `
	PaymentMethod           omit.Val[enums.OrganizationPlansPaymentMethod] `db:"payment_method" `
	StripeCustomer          omit.Val[string]                               `db:"stripe_customer" `
	StripeSubscription      omit.Val[string]                               `db:"stripe_subscription" `
	StripeCharge            omit.Val[string]                               `db:"stripe_charge" `
	UnsubscribedReason      omit.Val[string]                               `db:"unsubscribed_reason" `
	UnsubscribedRequestedAt omitnull.Val[time.Time]                        `db:"unsubscribed_requested_at" `
	UnsubscribedActuallyAt  omitnull.Val[time.Time]                        `db:"unsubscribed_actually_at" `
	IsPending               omit.Val[bool]                                 `db:"is_pending" `
	IsEnabled               omitnull.Val[bool]                             `db:"is_enabled" `
	ContractPrice           omit.Val[int32]                                `db:"contract_price" `
	ContractVersion         omit.Val[int32]                                `db:"contract_version" `
	ContractPeriod          omit.Val[int32]                                `db:"contract_period" `
	ContractUpdatedAt       omitnull.Val[time.Time]                        `db:"contract_updated_at" `
	ContractStartedAt       omitnull.Val[time.Time]                        `db:"contract_started_at" `
	ContractExpiredAt       omit.Val[time.Time]                            `db:"contract_expired_at" `
	CreatedAt               omit.Val[time.Time]                            `db:"created_at" `
	UpdatedAt               omit.Val[time.Time]                            `db:"updated_at" `
}

func (s OrganizationPlanSetter) SetColumns() []string {
	vals := make([]string, 0, 21)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.OrganizationID.IsValue() {
		vals = append(vals, "organization_id")
	}
	if s.OrganizationPlanBuyerID.IsValue() {
		vals = append(vals, "organization_plan_buyer_id")
	}
	if s.Plan.IsValue() {
		vals = append(vals, "plan")
	}
	if s.PaymentMethod.IsValue() {
		vals = append(vals, "payment_method")
	}
	if s.StripeCustomer.IsValue() {
		vals = append(vals, "stripe_customer")
	}
	if s.StripeSubscription.IsValue() {
		vals = append(vals, "stripe_subscription")
	}
	if s.StripeCharge.IsValue() {
		vals = append(vals, "stripe_charge")
	}
	if s.UnsubscribedReason.IsValue() {
		vals = append(vals, "unsubscribed_reason")
	}
	if !s.UnsubscribedRequestedAt.IsUnset() {
		vals = append(vals, "unsubscribed_requested_at")
	}
	if !s.UnsubscribedActuallyAt.IsUnset() {
		vals = append(vals, "unsubscribed_actually_at")
	}
	if s.IsPending.IsValue() {
		vals = append(vals, "is_pending")
	}
	if !s.IsEnabled.IsUnset() {
		vals = append(vals, "is_enabled")
	}
	if s.ContractPrice.IsValue() {
		vals = append(vals, "contract_price")
	}
	if s.ContractVersion.IsValue() {
		vals = append(vals, "contract_version")
	}
	if s.ContractPeriod.IsValue() {
		vals = append(vals, "contract_period")
	}
	if !s.ContractUpdatedAt.IsUnset() {
		vals = append(vals, "contract_updated_at")
	}
	if !s.ContractStartedAt.IsUnset() {
		vals = append(vals, "contract_started_at")
	}
	if s.ContractExpiredAt.IsValue() {
		vals = append(vals, "contract_expired_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrganizationPlanSetter) Overwrite(t *OrganizationPlan) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.OrganizationID.IsValue() {
		t.OrganizationID = s.OrganizationID.MustGet()
	}
	if s.OrganizationPlanBuyerID.IsValue() {
		t.OrganizationPlanBuyerID = s.OrganizationPlanBuyerID.MustGet()
	}
	if s.Plan.IsValue() {
		t.Plan = s.Plan.MustGet()
	}
	if s.PaymentMethod.IsValue() {
		t.PaymentMethod = s.PaymentMethod.MustGet()
	}
	if s.StripeCustomer.IsValue() {
		t.StripeCustomer = s.StripeCustomer.MustGet()
	}
	if s.StripeSubscription.IsValue() {
		t.StripeSubscription = s.StripeSubscription.MustGet()
	}
	if s.StripeCharge.IsValue() {
		t.StripeCharge = s.StripeCharge.MustGet()
	}
	if s.UnsubscribedReason.IsValue() {
		t.UnsubscribedReason = s.UnsubscribedReason.MustGet()
	}
	if !s.UnsubscribedRequestedAt.IsUnset() {
		t.UnsubscribedRequestedAt = s.UnsubscribedRequestedAt.MustGetNull()
	}
	if !s.UnsubscribedActuallyAt.IsUnset() {
		t.UnsubscribedActuallyAt = s.UnsubscribedActuallyAt.MustGetNull()
	}
	if s.IsPending.IsValue() {
		t.IsPending = s.IsPending.MustGet()
	}
	if !s.IsEnabled.IsUnset() {
		t.IsEnabled = s.IsEnabled.MustGetNull()
	}
	if s.ContractPrice.IsValue() {
		t.ContractPrice = s.ContractPrice.MustGet()
	}
	if s.ContractVersion.IsValue() {
		t.ContractVersion = s.ContractVersion.MustGet()
	}
	if s.ContractPeriod.IsValue() {
		t.ContractPeriod = s.ContractPeriod.MustGet()
	}
	if !s.ContractUpdatedAt.IsUnset() {
		t.ContractUpdatedAt = s.ContractUpdatedAt.MustGetNull()
	}
	if !s.ContractStartedAt.IsUnset() {
		t.ContractStartedAt = s.ContractStartedAt.MustGetNull()
	}
	if s.ContractExpiredAt.IsValue() {
		t.ContractExpiredAt = s.ContractExpiredAt.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OrganizationPlanSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return OrganizationPlans.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.OrganizationID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.OrganizationID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.OrganizationPlanBuyerID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.OrganizationPlanBuyerID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Plan.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Plan.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PaymentMethod.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PaymentMethod.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.StripeCustomer.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.StripeCustomer.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.StripeSubscription.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.StripeSubscription.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.StripeCharge.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.StripeCharge.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UnsubscribedReason.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UnsubscribedReason.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.UnsubscribedRequestedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UnsubscribedRequestedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.UnsubscribedActuallyAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UnsubscribedActuallyAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.IsPending.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsPending.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.IsEnabled.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.IsEnabled.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ContractPrice.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ContractPrice.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ContractVersion.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ContractVersion.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ContractPeriod.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ContractPeriod.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.ContractUpdatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ContractUpdatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(!s.ContractStartedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ContractStartedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ContractExpiredAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ContractExpiredAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s OrganizationPlanSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("organization_plans")...)
}

func (s OrganizationPlanSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 21)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.OrganizationID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "organization_id")...),
			mysql.Arg(s.OrganizationID),
		}})
	}

	if s.OrganizationPlanBuyerID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "organization_plan_buyer_id")...),
			mysql.Arg(s.OrganizationPlanBuyerID),
		}})
	}

	if s.Plan.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "plan")...),
			mysql.Arg(s.Plan),
		}})
	}

	if s.PaymentMethod.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "payment_method")...),
			mysql.Arg(s.PaymentMethod),
		}})
	}

	if s.StripeCustomer.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "stripe_customer")...),
			mysql.Arg(s.StripeCustomer),
		}})
	}

	if s.StripeSubscription.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "stripe_subscription")...),
			mysql.Arg(s.StripeSubscription),
		}})
	}

	if s.StripeCharge.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "stripe_charge")...),
			mysql.Arg(s.StripeCharge),
		}})
	}

	if s.UnsubscribedReason.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "unsubscribed_reason")...),
			mysql.Arg(s.UnsubscribedReason),
		}})
	}

	if !s.UnsubscribedRequestedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "unsubscribed_requested_at")...),
			mysql.Arg(s.UnsubscribedRequestedAt),
		}})
	}

	if !s.UnsubscribedActuallyAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "unsubscribed_actually_at")...),
			mysql.Arg(s.UnsubscribedActuallyAt),
		}})
	}

	if s.IsPending.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_pending")...),
			mysql.Arg(s.IsPending),
		}})
	}

	if !s.IsEnabled.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "is_enabled")...),
			mysql.Arg(s.IsEnabled),
		}})
	}

	if s.ContractPrice.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "contract_price")...),
			mysql.Arg(s.ContractPrice),
		}})
	}

	if s.ContractVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "contract_version")...),
			mysql.Arg(s.ContractVersion),
		}})
	}

	if s.ContractPeriod.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "contract_period")...),
			mysql.Arg(s.ContractPeriod),
		}})
	}

	if !s.ContractUpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "contract_updated_at")...),
			mysql.Arg(s.ContractUpdatedAt),
		}})
	}

	if !s.ContractStartedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "contract_started_at")...),
			mysql.Arg(s.ContractStartedAt),
		}})
	}

	if s.ContractExpiredAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "contract_expired_at")...),
			mysql.Arg(s.ContractExpiredAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrganizationPlan retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrganizationPlan(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*OrganizationPlan, error) {
	if len(cols) == 0 {
		return OrganizationPlans.Query(
			sm.Where(OrganizationPlans.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return OrganizationPlans.Query(
		sm.Where(OrganizationPlans.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(OrganizationPlans.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrganizationPlanExists checks the presence of a single record by primary key
func OrganizationPlanExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return OrganizationPlans.Query(
		sm.Where(OrganizationPlans.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after OrganizationPlan is retrieved from the database
func (o *OrganizationPlan) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrganizationPlans.AfterSelectHooks.RunHooks(ctx, exec, OrganizationPlanSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = OrganizationPlans.AfterInsertHooks.RunHooks(ctx, exec, OrganizationPlanSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = OrganizationPlans.AfterUpdateHooks.RunHooks(ctx, exec, OrganizationPlanSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = OrganizationPlans.AfterDeleteHooks.RunHooks(ctx, exec, OrganizationPlanSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the OrganizationPlan
func (o *OrganizationPlan) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *OrganizationPlan) pkEQ() dialect.Expression {
	return mysql.Quote("organization_plans", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the OrganizationPlan
func (o *OrganizationPlan) Update(ctx context.Context, exec bob.Executor, s *OrganizationPlanSetter) error {
	_, err := OrganizationPlans.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single OrganizationPlan record with an executor
func (o *OrganizationPlan) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := OrganizationPlans.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the OrganizationPlan using the executor
func (o *OrganizationPlan) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := OrganizationPlans.Query(
		sm.Where(OrganizationPlans.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrganizationPlanSlice is retrieved from the database
func (o OrganizationPlanSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrganizationPlans.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = OrganizationPlans.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = OrganizationPlans.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = OrganizationPlans.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrganizationPlanSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("organization_plans", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrganizationPlanSlice) copyMatchingRows(from ...*OrganizationPlan) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrganizationPlanSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrganizationPlans.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrganizationPlan:
				o.copyMatchingRows(retrieved)
			case []*OrganizationPlan:
				o.copyMatchingRows(retrieved...)
			case OrganizationPlanSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrganizationPlan or a slice of OrganizationPlan
				// then run the AfterUpdateHooks on the slice
				_, err = OrganizationPlans.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrganizationPlanSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrganizationPlans.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrganizationPlan:
				o.copyMatchingRows(retrieved)
			case []*OrganizationPlan:
				o.copyMatchingRows(retrieved...)
			case OrganizationPlanSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrganizationPlan or a slice of OrganizationPlan
				// then run the AfterDeleteHooks on the slice
				_, err = OrganizationPlans.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrganizationPlanSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrganizationPlanSetter) error {
	_, err := OrganizationPlans.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o OrganizationPlanSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OrganizationPlans.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrganizationPlanSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := OrganizationPlans.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Organization starts a query for related objects on organizations
func (o *OrganizationPlan) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	return Organizations.Query(append(mods,
		sm.Where(Organizations.Columns.ID.EQ(mysql.Arg(o.OrganizationID))),
	)...)
}

func (os OrganizationPlanSlice) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.OrganizationID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Organizations.Query(append(mods,
		sm.Where(mysql.Group(Organizations.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationPlanBuyer starts a query for related objects on organization_plan_buyers
func (o *OrganizationPlan) OrganizationPlanBuyer(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPlanBuyersQuery {
	return OrganizationPlanBuyers.Query(append(mods,
		sm.Where(OrganizationPlanBuyers.Columns.ID.EQ(mysql.Arg(o.OrganizationPlanBuyerID))),
	)...)
}

func (os OrganizationPlanSlice) OrganizationPlanBuyer(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPlanBuyersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.OrganizationPlanBuyerID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return OrganizationPlanBuyers.Query(append(mods,
		sm.Where(mysql.Group(OrganizationPlanBuyers.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachOrganizationPlanOrganization0(ctx context.Context, exec bob.Executor, count int, organizationPlan0 *OrganizationPlan, organization1 *Organization) (*OrganizationPlan, error) {
	setter := &OrganizationPlanSetter{
		OrganizationID: omit.From(organization1.ID),
	}

	err := organizationPlan0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationPlanOrganization0: %w", err)
	}

	return organizationPlan0, nil
}

func (organizationPlan0 *OrganizationPlan) InsertOrganization(ctx context.Context, exec bob.Executor, related *OrganizationSetter) error {
	var err error

	organization1, err := Organizations.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrganizationPlanOrganization0(ctx, exec, 1, organizationPlan0, organization1)
	if err != nil {
		return err
	}

	organizationPlan0.R.Organization = organization1

	organization1.R.OrganizationPlans = append(organization1.R.OrganizationPlans, organizationPlan0)

	return nil
}

func (organizationPlan0 *OrganizationPlan) AttachOrganization(ctx context.Context, exec bob.Executor, organization1 *Organization) error {
	var err error

	_, err = attachOrganizationPlanOrganization0(ctx, exec, 1, organizationPlan0, organization1)
	if err != nil {
		return err
	}

	organizationPlan0.R.Organization = organization1

	organization1.R.OrganizationPlans = append(organization1.R.OrganizationPlans, organizationPlan0)

	return nil
}

func attachOrganizationPlanOrganizationPlanBuyer0(ctx context.Context, exec bob.Executor, count int, organizationPlan0 *OrganizationPlan, organizationPlanBuyer1 *OrganizationPlanBuyer) (*OrganizationPlan, error) {
	setter := &OrganizationPlanSetter{
		OrganizationPlanBuyerID: omit.From(organizationPlanBuyer1.ID),
	}

	err := organizationPlan0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationPlanOrganizationPlanBuyer0: %w", err)
	}

	return organizationPlan0, nil
}

func (organizationPlan0 *OrganizationPlan) InsertOrganizationPlanBuyer(ctx context.Context, exec bob.Executor, related *OrganizationPlanBuyerSetter) error {
	var err error

	organizationPlanBuyer1, err := OrganizationPlanBuyers.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrganizationPlanOrganizationPlanBuyer0(ctx, exec, 1, organizationPlan0, organizationPlanBuyer1)
	if err != nil {
		return err
	}

	organizationPlan0.R.OrganizationPlanBuyer = organizationPlanBuyer1

	organizationPlanBuyer1.R.OrganizationPlans = append(organizationPlanBuyer1.R.OrganizationPlans, organizationPlan0)

	return nil
}

func (organizationPlan0 *OrganizationPlan) AttachOrganizationPlanBuyer(ctx context.Context, exec bob.Executor, organizationPlanBuyer1 *OrganizationPlanBuyer) error {
	var err error

	_, err = attachOrganizationPlanOrganizationPlanBuyer0(ctx, exec, 1, organizationPlan0, organizationPlanBuyer1)
	if err != nil {
		return err
	}

	organizationPlan0.R.OrganizationPlanBuyer = organizationPlanBuyer1

	organizationPlanBuyer1.R.OrganizationPlans = append(organizationPlanBuyer1.R.OrganizationPlans, organizationPlan0)

	return nil
}

type organizationPlanWhere[Q mysql.Filterable] struct {
	ID                      mysql.WhereMod[Q, int32]
	OrganizationID          mysql.WhereMod[Q, int32]
	OrganizationPlanBuyerID mysql.WhereMod[Q, int32]
	Plan                    mysql.WhereMod[Q, enums.OrganizationPlansPlan]
	PaymentMethod           mysql.WhereMod[Q, enums.OrganizationPlansPaymentMethod]
	StripeCustomer          mysql.WhereMod[Q, string]
	StripeSubscription      mysql.WhereMod[Q, string]
	StripeCharge            mysql.WhereMod[Q, string]
	UnsubscribedReason      mysql.WhereMod[Q, string]
	UnsubscribedRequestedAt mysql.WhereNullMod[Q, time.Time]
	UnsubscribedActuallyAt  mysql.WhereNullMod[Q, time.Time]
	IsPending               mysql.WhereMod[Q, bool]
	IsEnabled               mysql.WhereNullMod[Q, bool]
	ContractPrice           mysql.WhereMod[Q, int32]
	ContractVersion         mysql.WhereMod[Q, int32]
	ContractPeriod          mysql.WhereMod[Q, int32]
	ContractUpdatedAt       mysql.WhereNullMod[Q, time.Time]
	ContractStartedAt       mysql.WhereNullMod[Q, time.Time]
	ContractExpiredAt       mysql.WhereMod[Q, time.Time]
	CreatedAt               mysql.WhereMod[Q, time.Time]
	UpdatedAt               mysql.WhereMod[Q, time.Time]
}

func (organizationPlanWhere[Q]) AliasedAs(alias string) organizationPlanWhere[Q] {
	return buildOrganizationPlanWhere[Q](buildOrganizationPlanColumns(alias))
}

func buildOrganizationPlanWhere[Q mysql.Filterable](cols organizationPlanColumns) organizationPlanWhere[Q] {
	return organizationPlanWhere[Q]{
		ID:                      mysql.Where[Q, int32](cols.ID),
		OrganizationID:          mysql.Where[Q, int32](cols.OrganizationID),
		OrganizationPlanBuyerID: mysql.Where[Q, int32](cols.OrganizationPlanBuyerID),
		Plan:                    mysql.Where[Q, enums.OrganizationPlansPlan](cols.Plan),
		PaymentMethod:           mysql.Where[Q, enums.OrganizationPlansPaymentMethod](cols.PaymentMethod),
		StripeCustomer:          mysql.Where[Q, string](cols.StripeCustomer),
		StripeSubscription:      mysql.Where[Q, string](cols.StripeSubscription),
		StripeCharge:            mysql.Where[Q, string](cols.StripeCharge),
		UnsubscribedReason:      mysql.Where[Q, string](cols.UnsubscribedReason),
		UnsubscribedRequestedAt: mysql.WhereNull[Q, time.Time](cols.UnsubscribedRequestedAt),
		UnsubscribedActuallyAt:  mysql.WhereNull[Q, time.Time](cols.UnsubscribedActuallyAt),
		IsPending:               mysql.Where[Q, bool](cols.IsPending),
		IsEnabled:               mysql.WhereNull[Q, bool](cols.IsEnabled),
		ContractPrice:           mysql.Where[Q, int32](cols.ContractPrice),
		ContractVersion:         mysql.Where[Q, int32](cols.ContractVersion),
		ContractPeriod:          mysql.Where[Q, int32](cols.ContractPeriod),
		ContractUpdatedAt:       mysql.WhereNull[Q, time.Time](cols.ContractUpdatedAt),
		ContractStartedAt:       mysql.WhereNull[Q, time.Time](cols.ContractStartedAt),
		ContractExpiredAt:       mysql.Where[Q, time.Time](cols.ContractExpiredAt),
		CreatedAt:               mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:               mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *OrganizationPlan) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Organization":
		rel, ok := retrieved.(*Organization)
		if !ok {
			return fmt.Errorf("organizationPlan cannot load %T as %q", retrieved, name)
		}

		o.R.Organization = rel

		if rel != nil {
			rel.R.OrganizationPlans = OrganizationPlanSlice{o}
		}
		return nil
	case "OrganizationPlanBuyer":
		rel, ok := retrieved.(*OrganizationPlanBuyer)
		if !ok {
			return fmt.Errorf("organizationPlan cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationPlanBuyer = rel

		if rel != nil {
			rel.R.OrganizationPlans = OrganizationPlanSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("organizationPlan has no relationship %q", name)
	}
}

type organizationPlanPreloader struct {
	Organization          func(...mysql.PreloadOption) mysql.Preloader
	OrganizationPlanBuyer func(...mysql.PreloadOption) mysql.Preloader
}

func buildOrganizationPlanPreloader() organizationPlanPreloader {
	return organizationPlanPreloader{
		Organization: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*Organization, OrganizationSlice](mysql.PreloadRel{
				Name: "Organization",
				Sides: []mysql.PreloadSide{
					{
						From:        OrganizationPlans,
						To:          Organizations,
						FromColumns: []string{"organization_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Organizations.Columns.Names(), opts...)
		},
		OrganizationPlanBuyer: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*OrganizationPlanBuyer, OrganizationPlanBuyerSlice](mysql.PreloadRel{
				Name: "OrganizationPlanBuyer",
				Sides: []mysql.PreloadSide{
					{
						From:        OrganizationPlans,
						To:          OrganizationPlanBuyers,
						FromColumns: []string{"organization_plan_buyer_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, OrganizationPlanBuyers.Columns.Names(), opts...)
		},
	}
}

type organizationPlanThenLoader[Q orm.Loadable] struct {
	Organization          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationPlanBuyer func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrganizationPlanThenLoader[Q orm.Loadable]() organizationPlanThenLoader[Q] {
	type OrganizationLoadInterface interface {
		LoadOrganization(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationPlanBuyerLoadInterface interface {
		LoadOrganizationPlanBuyer(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return organizationPlanThenLoader[Q]{
		Organization: thenLoadBuilder[Q](
			"Organization",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganization(ctx, exec, mods...)
			},
		),
		OrganizationPlanBuyer: thenLoadBuilder[Q](
			"OrganizationPlanBuyer",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationPlanBuyerLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationPlanBuyer(ctx, exec, mods...)
			},
		),
	}
}

// LoadOrganization loads the organizationPlan's Organization into the .R struct
func (o *OrganizationPlan) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Organization = nil

	related, err := o.Organization(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.OrganizationPlans = OrganizationPlanSlice{o}

	o.R.Organization = related
	return nil
}

// LoadOrganization loads the organizationPlan's Organization into the .R struct
func (os OrganizationPlanSlice) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizations, err := os.Organization(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizations {

			if !(o.OrganizationID == rel.ID) {
				continue
			}

			rel.R.OrganizationPlans = append(rel.R.OrganizationPlans, o)

			o.R.Organization = rel
			break
		}
	}

	return nil
}

// LoadOrganizationPlanBuyer loads the organizationPlan's OrganizationPlanBuyer into the .R struct
func (o *OrganizationPlan) LoadOrganizationPlanBuyer(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationPlanBuyer = nil

	related, err := o.OrganizationPlanBuyer(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.OrganizationPlans = OrganizationPlanSlice{o}

	o.R.OrganizationPlanBuyer = related
	return nil
}

// LoadOrganizationPlanBuyer loads the organizationPlan's OrganizationPlanBuyer into the .R struct
func (os OrganizationPlanSlice) LoadOrganizationPlanBuyer(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationPlanBuyers, err := os.OrganizationPlanBuyer(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationPlanBuyers {

			if !(o.OrganizationPlanBuyerID == rel.ID) {
				continue
			}

			rel.R.OrganizationPlans = append(rel.R.OrganizationPlans, o)

			o.R.OrganizationPlanBuyer = rel
			break
		}
	}

	return nil
}

type organizationPlanJoins[Q dialect.Joinable] struct {
	typ                   string
	Organization          modAs[Q, organizationColumns]
	OrganizationPlanBuyer modAs[Q, organizationPlanBuyerColumns]
}

func (j organizationPlanJoins[Q]) aliasedAs(alias string) organizationPlanJoins[Q] {
	return buildOrganizationPlanJoins[Q](buildOrganizationPlanColumns(alias), j.typ)
}

func buildOrganizationPlanJoins[Q dialect.Joinable](cols organizationPlanColumns, typ string) organizationPlanJoins[Q] {
	return organizationPlanJoins[Q]{
		typ: typ,
		Organization: modAs[Q, organizationColumns]{
			c: Organizations.Columns,
			f: func(to organizationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Organizations.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OrganizationID),
					))
				}

				return mods
			},
		},
		OrganizationPlanBuyer: modAs[Q, organizationPlanBuyerColumns]{
			c: OrganizationPlanBuyers.Columns,
			f: func(to organizationPlanBuyerColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationPlanBuyers.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OrganizationPlanBuyerID),
					))
				}

				return mods
			},
		},
	}
}
