// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testmodels

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// OrganizationPlanBuyer is an object representing the database table.
type OrganizationPlanBuyer struct {
	ID int32 `db:"id,pk,autoincr" `
	// use in contract
	CompanyName string `db:"company_name" `
	// use in contract
	PhoneNumber string `db:"phone_number" `
	// use in contract
	Email string `db:"email" `
	// use in contract
	Representative string `db:"representative" `
	// use in contract
	UserName string `db:"user_name" `
	// use in contract
	Postcode string `db:"postcode" `
	// use in contract
	Address1 string `db:"address1" `
	// use in contract
	Address2 string `db:"address2" `
	// use in contract
	InvoicePostcode string `db:"invoice_postcode" `
	// use in contract
	InvoiceAddress1 string `db:"invoice_address1" `
	// use in contract
	InvoiceAddress2 string `db:"invoice_address2" `
	// use in contract
	InvoiceUserName string `db:"invoice_user_name" `
	// use in contract
	InvoiceEmail string    `db:"invoice_email" `
	CreatedAt    time.Time `db:"created_at" `
	UpdatedAt    time.Time `db:"updated_at" `

	R organizationPlanBuyerR `db:"-" `
}

// OrganizationPlanBuyerSlice is an alias for a slice of pointers to OrganizationPlanBuyer.
// This should almost always be used instead of []*OrganizationPlanBuyer.
type OrganizationPlanBuyerSlice []*OrganizationPlanBuyer

// OrganizationPlanBuyers contains methods to work with the organization_plan_buyers table
var OrganizationPlanBuyers = mysql.NewTablex[*OrganizationPlanBuyer, OrganizationPlanBuyerSlice, *OrganizationPlanBuyerSetter]("organization_plan_buyers", buildOrganizationPlanBuyerColumns("organization_plan_buyers"), []string{"id"})

// OrganizationPlanBuyersQuery is a query on the organization_plan_buyers table
type OrganizationPlanBuyersQuery = *mysql.ViewQuery[*OrganizationPlanBuyer, OrganizationPlanBuyerSlice]

// organizationPlanBuyerR is where relationships are stored.
type organizationPlanBuyerR struct {
	OrganizationPlans OrganizationPlanSlice // fk_organization_plans_organization_plan_buyer_id
}

func buildOrganizationPlanBuyerColumns(alias string) organizationPlanBuyerColumns {
	return organizationPlanBuyerColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "company_name", "phone_number", "email", "representative", "user_name", "postcode", "address1", "address2", "invoice_postcode", "invoice_address1", "invoice_address2", "invoice_user_name", "invoice_email", "created_at", "updated_at",
		).WithParent("organization_plan_buyers"),
		tableAlias:      alias,
		ID:              mysql.Quote(alias, "id"),
		CompanyName:     mysql.Quote(alias, "company_name"),
		PhoneNumber:     mysql.Quote(alias, "phone_number"),
		Email:           mysql.Quote(alias, "email"),
		Representative:  mysql.Quote(alias, "representative"),
		UserName:        mysql.Quote(alias, "user_name"),
		Postcode:        mysql.Quote(alias, "postcode"),
		Address1:        mysql.Quote(alias, "address1"),
		Address2:        mysql.Quote(alias, "address2"),
		InvoicePostcode: mysql.Quote(alias, "invoice_postcode"),
		InvoiceAddress1: mysql.Quote(alias, "invoice_address1"),
		InvoiceAddress2: mysql.Quote(alias, "invoice_address2"),
		InvoiceUserName: mysql.Quote(alias, "invoice_user_name"),
		InvoiceEmail:    mysql.Quote(alias, "invoice_email"),
		CreatedAt:       mysql.Quote(alias, "created_at"),
		UpdatedAt:       mysql.Quote(alias, "updated_at"),
	}
}

type organizationPlanBuyerColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              mysql.Expression
	CompanyName     mysql.Expression
	PhoneNumber     mysql.Expression
	Email           mysql.Expression
	Representative  mysql.Expression
	UserName        mysql.Expression
	Postcode        mysql.Expression
	Address1        mysql.Expression
	Address2        mysql.Expression
	InvoicePostcode mysql.Expression
	InvoiceAddress1 mysql.Expression
	InvoiceAddress2 mysql.Expression
	InvoiceUserName mysql.Expression
	InvoiceEmail    mysql.Expression
	CreatedAt       mysql.Expression
	UpdatedAt       mysql.Expression
}

func (c organizationPlanBuyerColumns) Alias() string {
	return c.tableAlias
}

func (organizationPlanBuyerColumns) AliasedAs(alias string) organizationPlanBuyerColumns {
	return buildOrganizationPlanBuyerColumns(alias)
}

// OrganizationPlanBuyerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrganizationPlanBuyerSetter struct {
	ID              omit.Val[int32]     `db:"id,pk,autoincr" `
	CompanyName     omit.Val[string]    `db:"company_name" `
	PhoneNumber     omit.Val[string]    `db:"phone_number" `
	Email           omit.Val[string]    `db:"email" `
	Representative  omit.Val[string]    `db:"representative" `
	UserName        omit.Val[string]    `db:"user_name" `
	Postcode        omit.Val[string]    `db:"postcode" `
	Address1        omit.Val[string]    `db:"address1" `
	Address2        omit.Val[string]    `db:"address2" `
	InvoicePostcode omit.Val[string]    `db:"invoice_postcode" `
	InvoiceAddress1 omit.Val[string]    `db:"invoice_address1" `
	InvoiceAddress2 omit.Val[string]    `db:"invoice_address2" `
	InvoiceUserName omit.Val[string]    `db:"invoice_user_name" `
	InvoiceEmail    omit.Val[string]    `db:"invoice_email" `
	CreatedAt       omit.Val[time.Time] `db:"created_at" `
	UpdatedAt       omit.Val[time.Time] `db:"updated_at" `
}

func (s OrganizationPlanBuyerSetter) SetColumns() []string {
	vals := make([]string, 0, 16)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.CompanyName.IsValue() {
		vals = append(vals, "company_name")
	}
	if s.PhoneNumber.IsValue() {
		vals = append(vals, "phone_number")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.Representative.IsValue() {
		vals = append(vals, "representative")
	}
	if s.UserName.IsValue() {
		vals = append(vals, "user_name")
	}
	if s.Postcode.IsValue() {
		vals = append(vals, "postcode")
	}
	if s.Address1.IsValue() {
		vals = append(vals, "address1")
	}
	if s.Address2.IsValue() {
		vals = append(vals, "address2")
	}
	if s.InvoicePostcode.IsValue() {
		vals = append(vals, "invoice_postcode")
	}
	if s.InvoiceAddress1.IsValue() {
		vals = append(vals, "invoice_address1")
	}
	if s.InvoiceAddress2.IsValue() {
		vals = append(vals, "invoice_address2")
	}
	if s.InvoiceUserName.IsValue() {
		vals = append(vals, "invoice_user_name")
	}
	if s.InvoiceEmail.IsValue() {
		vals = append(vals, "invoice_email")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrganizationPlanBuyerSetter) Overwrite(t *OrganizationPlanBuyer) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.CompanyName.IsValue() {
		t.CompanyName = s.CompanyName.MustGet()
	}
	if s.PhoneNumber.IsValue() {
		t.PhoneNumber = s.PhoneNumber.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.Representative.IsValue() {
		t.Representative = s.Representative.MustGet()
	}
	if s.UserName.IsValue() {
		t.UserName = s.UserName.MustGet()
	}
	if s.Postcode.IsValue() {
		t.Postcode = s.Postcode.MustGet()
	}
	if s.Address1.IsValue() {
		t.Address1 = s.Address1.MustGet()
	}
	if s.Address2.IsValue() {
		t.Address2 = s.Address2.MustGet()
	}
	if s.InvoicePostcode.IsValue() {
		t.InvoicePostcode = s.InvoicePostcode.MustGet()
	}
	if s.InvoiceAddress1.IsValue() {
		t.InvoiceAddress1 = s.InvoiceAddress1.MustGet()
	}
	if s.InvoiceAddress2.IsValue() {
		t.InvoiceAddress2 = s.InvoiceAddress2.MustGet()
	}
	if s.InvoiceUserName.IsValue() {
		t.InvoiceUserName = s.InvoiceUserName.MustGet()
	}
	if s.InvoiceEmail.IsValue() {
		t.InvoiceEmail = s.InvoiceEmail.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OrganizationPlanBuyerSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return OrganizationPlanBuyers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CompanyName.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CompanyName.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.PhoneNumber.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PhoneNumber.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Email.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Email.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Representative.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Representative.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UserName.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UserName.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Postcode.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Postcode.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Address1.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Address1.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.Address2.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Address2.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.InvoicePostcode.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.InvoicePostcode.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.InvoiceAddress1.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.InvoiceAddress1.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.InvoiceAddress2.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.InvoiceAddress2.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.InvoiceUserName.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.InvoiceUserName.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.InvoiceEmail.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.InvoiceEmail.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.CreatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
			if !(s.UpdatedAt.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s OrganizationPlanBuyerSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("organization_plan_buyers")...)
}

func (s OrganizationPlanBuyerSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 16)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.CompanyName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "company_name")...),
			mysql.Arg(s.CompanyName),
		}})
	}

	if s.PhoneNumber.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "phone_number")...),
			mysql.Arg(s.PhoneNumber),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "email")...),
			mysql.Arg(s.Email),
		}})
	}

	if s.Representative.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "representative")...),
			mysql.Arg(s.Representative),
		}})
	}

	if s.UserName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "user_name")...),
			mysql.Arg(s.UserName),
		}})
	}

	if s.Postcode.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "postcode")...),
			mysql.Arg(s.Postcode),
		}})
	}

	if s.Address1.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "address1")...),
			mysql.Arg(s.Address1),
		}})
	}

	if s.Address2.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "address2")...),
			mysql.Arg(s.Address2),
		}})
	}

	if s.InvoicePostcode.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "invoice_postcode")...),
			mysql.Arg(s.InvoicePostcode),
		}})
	}

	if s.InvoiceAddress1.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "invoice_address1")...),
			mysql.Arg(s.InvoiceAddress1),
		}})
	}

	if s.InvoiceAddress2.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "invoice_address2")...),
			mysql.Arg(s.InvoiceAddress2),
		}})
	}

	if s.InvoiceUserName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "invoice_user_name")...),
			mysql.Arg(s.InvoiceUserName),
		}})
	}

	if s.InvoiceEmail.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "invoice_email")...),
			mysql.Arg(s.InvoiceEmail),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrganizationPlanBuyer retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrganizationPlanBuyer(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*OrganizationPlanBuyer, error) {
	if len(cols) == 0 {
		return OrganizationPlanBuyers.Query(
			sm.Where(OrganizationPlanBuyers.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return OrganizationPlanBuyers.Query(
		sm.Where(OrganizationPlanBuyers.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(OrganizationPlanBuyers.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrganizationPlanBuyerExists checks the presence of a single record by primary key
func OrganizationPlanBuyerExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return OrganizationPlanBuyers.Query(
		sm.Where(OrganizationPlanBuyers.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after OrganizationPlanBuyer is retrieved from the database
func (o *OrganizationPlanBuyer) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrganizationPlanBuyers.AfterSelectHooks.RunHooks(ctx, exec, OrganizationPlanBuyerSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = OrganizationPlanBuyers.AfterInsertHooks.RunHooks(ctx, exec, OrganizationPlanBuyerSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = OrganizationPlanBuyers.AfterUpdateHooks.RunHooks(ctx, exec, OrganizationPlanBuyerSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = OrganizationPlanBuyers.AfterDeleteHooks.RunHooks(ctx, exec, OrganizationPlanBuyerSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the OrganizationPlanBuyer
func (o *OrganizationPlanBuyer) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *OrganizationPlanBuyer) pkEQ() dialect.Expression {
	return mysql.Quote("organization_plan_buyers", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the OrganizationPlanBuyer
func (o *OrganizationPlanBuyer) Update(ctx context.Context, exec bob.Executor, s *OrganizationPlanBuyerSetter) error {
	_, err := OrganizationPlanBuyers.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single OrganizationPlanBuyer record with an executor
func (o *OrganizationPlanBuyer) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := OrganizationPlanBuyers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the OrganizationPlanBuyer using the executor
func (o *OrganizationPlanBuyer) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := OrganizationPlanBuyers.Query(
		sm.Where(OrganizationPlanBuyers.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrganizationPlanBuyerSlice is retrieved from the database
func (o OrganizationPlanBuyerSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrganizationPlanBuyers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = OrganizationPlanBuyers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = OrganizationPlanBuyers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = OrganizationPlanBuyers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrganizationPlanBuyerSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("organization_plan_buyers", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrganizationPlanBuyerSlice) copyMatchingRows(from ...*OrganizationPlanBuyer) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrganizationPlanBuyerSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrganizationPlanBuyers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrganizationPlanBuyer:
				o.copyMatchingRows(retrieved)
			case []*OrganizationPlanBuyer:
				o.copyMatchingRows(retrieved...)
			case OrganizationPlanBuyerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrganizationPlanBuyer or a slice of OrganizationPlanBuyer
				// then run the AfterUpdateHooks on the slice
				_, err = OrganizationPlanBuyers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrganizationPlanBuyerSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrganizationPlanBuyers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrganizationPlanBuyer:
				o.copyMatchingRows(retrieved)
			case []*OrganizationPlanBuyer:
				o.copyMatchingRows(retrieved...)
			case OrganizationPlanBuyerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrganizationPlanBuyer or a slice of OrganizationPlanBuyer
				// then run the AfterDeleteHooks on the slice
				_, err = OrganizationPlanBuyers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrganizationPlanBuyerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrganizationPlanBuyerSetter) error {
	_, err := OrganizationPlanBuyers.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o OrganizationPlanBuyerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OrganizationPlanBuyers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrganizationPlanBuyerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := OrganizationPlanBuyers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// OrganizationPlans starts a query for related objects on organization_plans
func (o *OrganizationPlanBuyer) OrganizationPlans(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPlansQuery {
	return OrganizationPlans.Query(append(mods,
		sm.Where(OrganizationPlans.Columns.OrganizationPlanBuyerID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os OrganizationPlanBuyerSlice) OrganizationPlans(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPlansQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return OrganizationPlans.Query(append(mods,
		sm.Where(mysql.Group(OrganizationPlans.Columns.OrganizationPlanBuyerID).OP("IN", PKArgExpr)),
	)...)
}

func insertOrganizationPlanBuyerOrganizationPlans0(ctx context.Context, exec bob.Executor, organizationPlans1 []*OrganizationPlanSetter, organizationPlanBuyer0 *OrganizationPlanBuyer) (OrganizationPlanSlice, error) {
	for i := range organizationPlans1 {
		organizationPlans1[i].OrganizationPlanBuyerID = omit.From(organizationPlanBuyer0.ID)
	}

	ret, err := OrganizationPlans.Insert(bob.ToMods(organizationPlans1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationPlanBuyerOrganizationPlans0: %w", err)
	}

	return ret, nil
}

func attachOrganizationPlanBuyerOrganizationPlans0(ctx context.Context, exec bob.Executor, count int, organizationPlans1 OrganizationPlanSlice, organizationPlanBuyer0 *OrganizationPlanBuyer) (OrganizationPlanSlice, error) {
	setter := &OrganizationPlanSetter{
		OrganizationPlanBuyerID: omit.From(organizationPlanBuyer0.ID),
	}

	err := organizationPlans1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationPlanBuyerOrganizationPlans0: %w", err)
	}

	return organizationPlans1, nil
}

func (organizationPlanBuyer0 *OrganizationPlanBuyer) InsertOrganizationPlans(ctx context.Context, exec bob.Executor, related ...*OrganizationPlanSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	organizationPlans1, err := insertOrganizationPlanBuyerOrganizationPlans0(ctx, exec, related, organizationPlanBuyer0)
	if err != nil {
		return err
	}

	organizationPlanBuyer0.R.OrganizationPlans = append(organizationPlanBuyer0.R.OrganizationPlans, organizationPlans1...)

	for _, rel := range organizationPlans1 {
		rel.R.OrganizationPlanBuyer = organizationPlanBuyer0
	}
	return nil
}

func (organizationPlanBuyer0 *OrganizationPlanBuyer) AttachOrganizationPlans(ctx context.Context, exec bob.Executor, related ...*OrganizationPlan) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	organizationPlans1 := OrganizationPlanSlice(related)

	_, err = attachOrganizationPlanBuyerOrganizationPlans0(ctx, exec, len(related), organizationPlans1, organizationPlanBuyer0)
	if err != nil {
		return err
	}

	organizationPlanBuyer0.R.OrganizationPlans = append(organizationPlanBuyer0.R.OrganizationPlans, organizationPlans1...)

	for _, rel := range related {
		rel.R.OrganizationPlanBuyer = organizationPlanBuyer0
	}

	return nil
}

type organizationPlanBuyerWhere[Q mysql.Filterable] struct {
	ID              mysql.WhereMod[Q, int32]
	CompanyName     mysql.WhereMod[Q, string]
	PhoneNumber     mysql.WhereMod[Q, string]
	Email           mysql.WhereMod[Q, string]
	Representative  mysql.WhereMod[Q, string]
	UserName        mysql.WhereMod[Q, string]
	Postcode        mysql.WhereMod[Q, string]
	Address1        mysql.WhereMod[Q, string]
	Address2        mysql.WhereMod[Q, string]
	InvoicePostcode mysql.WhereMod[Q, string]
	InvoiceAddress1 mysql.WhereMod[Q, string]
	InvoiceAddress2 mysql.WhereMod[Q, string]
	InvoiceUserName mysql.WhereMod[Q, string]
	InvoiceEmail    mysql.WhereMod[Q, string]
	CreatedAt       mysql.WhereMod[Q, time.Time]
	UpdatedAt       mysql.WhereMod[Q, time.Time]
}

func (organizationPlanBuyerWhere[Q]) AliasedAs(alias string) organizationPlanBuyerWhere[Q] {
	return buildOrganizationPlanBuyerWhere[Q](buildOrganizationPlanBuyerColumns(alias))
}

func buildOrganizationPlanBuyerWhere[Q mysql.Filterable](cols organizationPlanBuyerColumns) organizationPlanBuyerWhere[Q] {
	return organizationPlanBuyerWhere[Q]{
		ID:              mysql.Where[Q, int32](cols.ID),
		CompanyName:     mysql.Where[Q, string](cols.CompanyName),
		PhoneNumber:     mysql.Where[Q, string](cols.PhoneNumber),
		Email:           mysql.Where[Q, string](cols.Email),
		Representative:  mysql.Where[Q, string](cols.Representative),
		UserName:        mysql.Where[Q, string](cols.UserName),
		Postcode:        mysql.Where[Q, string](cols.Postcode),
		Address1:        mysql.Where[Q, string](cols.Address1),
		Address2:        mysql.Where[Q, string](cols.Address2),
		InvoicePostcode: mysql.Where[Q, string](cols.InvoicePostcode),
		InvoiceAddress1: mysql.Where[Q, string](cols.InvoiceAddress1),
		InvoiceAddress2: mysql.Where[Q, string](cols.InvoiceAddress2),
		InvoiceUserName: mysql.Where[Q, string](cols.InvoiceUserName),
		InvoiceEmail:    mysql.Where[Q, string](cols.InvoiceEmail),
		CreatedAt:       mysql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:       mysql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *OrganizationPlanBuyer) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "OrganizationPlans":
		rels, ok := retrieved.(OrganizationPlanSlice)
		if !ok {
			return fmt.Errorf("organizationPlanBuyer cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationPlans = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.OrganizationPlanBuyer = o
			}
		}
		return nil
	default:
		return fmt.Errorf("organizationPlanBuyer has no relationship %q", name)
	}
}

type organizationPlanBuyerPreloader struct{}

func buildOrganizationPlanBuyerPreloader() organizationPlanBuyerPreloader {
	return organizationPlanBuyerPreloader{}
}

type organizationPlanBuyerThenLoader[Q orm.Loadable] struct {
	OrganizationPlans func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrganizationPlanBuyerThenLoader[Q orm.Loadable]() organizationPlanBuyerThenLoader[Q] {
	type OrganizationPlansLoadInterface interface {
		LoadOrganizationPlans(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return organizationPlanBuyerThenLoader[Q]{
		OrganizationPlans: thenLoadBuilder[Q](
			"OrganizationPlans",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationPlansLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationPlans(ctx, exec, mods...)
			},
		),
	}
}

// LoadOrganizationPlans loads the organizationPlanBuyer's OrganizationPlans into the .R struct
func (o *OrganizationPlanBuyer) LoadOrganizationPlans(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationPlans = nil

	related, err := o.OrganizationPlans(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.OrganizationPlanBuyer = o
	}

	o.R.OrganizationPlans = related
	return nil
}

// LoadOrganizationPlans loads the organizationPlanBuyer's OrganizationPlans into the .R struct
func (os OrganizationPlanBuyerSlice) LoadOrganizationPlans(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationPlans, err := os.OrganizationPlans(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OrganizationPlans = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationPlans {

			if !(o.ID == rel.OrganizationPlanBuyerID) {
				continue
			}

			rel.R.OrganizationPlanBuyer = o

			o.R.OrganizationPlans = append(o.R.OrganizationPlans, rel)
		}
	}

	return nil
}

type organizationPlanBuyerJoins[Q dialect.Joinable] struct {
	typ               string
	OrganizationPlans modAs[Q, organizationPlanColumns]
}

func (j organizationPlanBuyerJoins[Q]) aliasedAs(alias string) organizationPlanBuyerJoins[Q] {
	return buildOrganizationPlanBuyerJoins[Q](buildOrganizationPlanBuyerColumns(alias), j.typ)
}

func buildOrganizationPlanBuyerJoins[Q dialect.Joinable](cols organizationPlanBuyerColumns, typ string) organizationPlanBuyerJoins[Q] {
	return organizationPlanBuyerJoins[Q]{
		typ: typ,
		OrganizationPlans: modAs[Q, organizationPlanColumns]{
			c: OrganizationPlans.Columns,
			f: func(to organizationPlanColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationPlans.Name().As(to.Alias())).On(
						to.OrganizationPlanBuyerID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
