// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package testenums

import (
	"database/sql/driver"
	"fmt"
)

// Enum values for BannersState
const (
	BannersStateBS1 BannersState = "BS_1"
	BannersStateBS2 BannersState = "BS_2"
	BannersStateBS3 BannersState = "BS_3"
	BannersStateBS4 BannersState = "BS_4"
	BannersStateBS5 BannersState = "BS_5"
	BannersStateBS6 BannersState = "BS_6"
	BannersStateBS7 BannersState = "BS_7"
	BannersStateBS8 BannersState = "BS_8"
	BannersStateBS9 BannersState = "BS_9"
)

func AllBannersState() []BannersState {
	return []BannersState{
		BannersStateBS1,
		BannersStateBS2,
		BannersStateBS3,
		BannersStateBS4,
		BannersStateBS5,
		BannersStateBS6,
		BannersStateBS7,
		BannersStateBS8,
		BannersStateBS9,
	}
}

type BannersState string

func (e BannersState) String() string {
	return string(e)
}

func (e BannersState) Valid() bool {
	switch e {
	case BannersStateBS1,
		BannersStateBS2,
		BannersStateBS3,
		BannersStateBS4,
		BannersStateBS5,
		BannersStateBS6,
		BannersStateBS7,
		BannersStateBS8,
		BannersStateBS9:
		return true
	default:
		return false
	}
}

// useful when testing in other packages
func (e BannersState) All() []BannersState {
	return AllBannersState()
}

func (e BannersState) MarshalText() ([]byte, error) {
	return []byte(e), nil
}

func (e *BannersState) UnmarshalText(text []byte) error {
	return e.Scan(text)
}

func (e BannersState) MarshalBinary() ([]byte, error) {
	return []byte(e), nil
}

func (e *BannersState) UnmarshalBinary(data []byte) error {
	return e.Scan(data)
}

func (e BannersState) Value() (driver.Value, error) {
	return string(e), nil
}

func (e *BannersState) Scan(value any) error {
	switch x := value.(type) {
	case string:
		*e = BannersState(x)
	case []byte:
		*e = BannersState(x)
	case nil:
		return fmt.Errorf("cannot nil into BannersState")
	default:
		return fmt.Errorf("cannot scan type %T: %v", value, value)
	}

	if !e.Valid() {
		return fmt.Errorf("invalid BannersState value: %s", *e)
	}

	return nil
}

// Enum values for OrganizationPlansPaymentMethod
const (
	OrganizationPlansPaymentMethodPM1 OrganizationPlansPaymentMethod = "PM_1"
	OrganizationPlansPaymentMethodPM2 OrganizationPlansPaymentMethod = "PM_2"
)

func AllOrganizationPlansPaymentMethod() []OrganizationPlansPaymentMethod {
	return []OrganizationPlansPaymentMethod{
		OrganizationPlansPaymentMethodPM1,
		OrganizationPlansPaymentMethodPM2,
	}
}

type OrganizationPlansPaymentMethod string

func (e OrganizationPlansPaymentMethod) String() string {
	return string(e)
}

func (e OrganizationPlansPaymentMethod) Valid() bool {
	switch e {
	case OrganizationPlansPaymentMethodPM1,
		OrganizationPlansPaymentMethodPM2:
		return true
	default:
		return false
	}
}

// useful when testing in other packages
func (e OrganizationPlansPaymentMethod) All() []OrganizationPlansPaymentMethod {
	return AllOrganizationPlansPaymentMethod()
}

func (e OrganizationPlansPaymentMethod) MarshalText() ([]byte, error) {
	return []byte(e), nil
}

func (e *OrganizationPlansPaymentMethod) UnmarshalText(text []byte) error {
	return e.Scan(text)
}

func (e OrganizationPlansPaymentMethod) MarshalBinary() ([]byte, error) {
	return []byte(e), nil
}

func (e *OrganizationPlansPaymentMethod) UnmarshalBinary(data []byte) error {
	return e.Scan(data)
}

func (e OrganizationPlansPaymentMethod) Value() (driver.Value, error) {
	return string(e), nil
}

func (e *OrganizationPlansPaymentMethod) Scan(value any) error {
	switch x := value.(type) {
	case string:
		*e = OrganizationPlansPaymentMethod(x)
	case []byte:
		*e = OrganizationPlansPaymentMethod(x)
	case nil:
		return fmt.Errorf("cannot nil into OrganizationPlansPaymentMethod")
	default:
		return fmt.Errorf("cannot scan type %T: %v", value, value)
	}

	if !e.Valid() {
		return fmt.Errorf("invalid OrganizationPlansPaymentMethod value: %s", *e)
	}

	return nil
}

// Enum values for OrganizationPlansPlan
const (
	OrganizationPlansPlanPL1  OrganizationPlansPlan = "PL_1"
	OrganizationPlansPlanPL2  OrganizationPlansPlan = "PL_2"
	OrganizationPlansPlanPL3  OrganizationPlansPlan = "PL_3"
	OrganizationPlansPlanPL4  OrganizationPlansPlan = "PL_4"
	OrganizationPlansPlanPL5  OrganizationPlansPlan = "PL_5"
	OrganizationPlansPlanPL6  OrganizationPlansPlan = "PL_6"
	OrganizationPlansPlanPL7  OrganizationPlansPlan = "PL_7"
	OrganizationPlansPlanPL8  OrganizationPlansPlan = "PL_8"
	OrganizationPlansPlanPL9  OrganizationPlansPlan = "PL_9"
	OrganizationPlansPlanPL10 OrganizationPlansPlan = "PL_10"
	OrganizationPlansPlanPL11 OrganizationPlansPlan = "PL_11"
	OrganizationPlansPlanPL12 OrganizationPlansPlan = "PL_12"
	OrganizationPlansPlanPL13 OrganizationPlansPlan = "PL_13"
	OrganizationPlansPlanPL14 OrganizationPlansPlan = "PL_14"
	OrganizationPlansPlanPL15 OrganizationPlansPlan = "PL_15"
	OrganizationPlansPlanPL16 OrganizationPlansPlan = "PL_16"
	OrganizationPlansPlanPL17 OrganizationPlansPlan = "PL_17"
	OrganizationPlansPlanPL18 OrganizationPlansPlan = "PL_18"
	OrganizationPlansPlanPL19 OrganizationPlansPlan = "PL_19"
	OrganizationPlansPlanPL20 OrganizationPlansPlan = "PL_20"
	OrganizationPlansPlanPL21 OrganizationPlansPlan = "PL_21"
)

func AllOrganizationPlansPlan() []OrganizationPlansPlan {
	return []OrganizationPlansPlan{
		OrganizationPlansPlanPL1,
		OrganizationPlansPlanPL2,
		OrganizationPlansPlanPL3,
		OrganizationPlansPlanPL4,
		OrganizationPlansPlanPL5,
		OrganizationPlansPlanPL6,
		OrganizationPlansPlanPL7,
		OrganizationPlansPlanPL8,
		OrganizationPlansPlanPL9,
		OrganizationPlansPlanPL10,
		OrganizationPlansPlanPL11,
		OrganizationPlansPlanPL12,
		OrganizationPlansPlanPL13,
		OrganizationPlansPlanPL14,
		OrganizationPlansPlanPL15,
		OrganizationPlansPlanPL16,
		OrganizationPlansPlanPL17,
		OrganizationPlansPlanPL18,
		OrganizationPlansPlanPL19,
		OrganizationPlansPlanPL20,
		OrganizationPlansPlanPL21,
	}
}

type OrganizationPlansPlan string

func (e OrganizationPlansPlan) String() string {
	return string(e)
}

func (e OrganizationPlansPlan) Valid() bool {
	switch e {
	case OrganizationPlansPlanPL1,
		OrganizationPlansPlanPL2,
		OrganizationPlansPlanPL3,
		OrganizationPlansPlanPL4,
		OrganizationPlansPlanPL5,
		OrganizationPlansPlanPL6,
		OrganizationPlansPlanPL7,
		OrganizationPlansPlanPL8,
		OrganizationPlansPlanPL9,
		OrganizationPlansPlanPL10,
		OrganizationPlansPlanPL11,
		OrganizationPlansPlanPL12,
		OrganizationPlansPlanPL13,
		OrganizationPlansPlanPL14,
		OrganizationPlansPlanPL15,
		OrganizationPlansPlanPL16,
		OrganizationPlansPlanPL17,
		OrganizationPlansPlanPL18,
		OrganizationPlansPlanPL19,
		OrganizationPlansPlanPL20,
		OrganizationPlansPlanPL21:
		return true
	default:
		return false
	}
}

// useful when testing in other packages
func (e OrganizationPlansPlan) All() []OrganizationPlansPlan {
	return AllOrganizationPlansPlan()
}

func (e OrganizationPlansPlan) MarshalText() ([]byte, error) {
	return []byte(e), nil
}

func (e *OrganizationPlansPlan) UnmarshalText(text []byte) error {
	return e.Scan(text)
}

func (e OrganizationPlansPlan) MarshalBinary() ([]byte, error) {
	return []byte(e), nil
}

func (e *OrganizationPlansPlan) UnmarshalBinary(data []byte) error {
	return e.Scan(data)
}

func (e OrganizationPlansPlan) Value() (driver.Value, error) {
	return string(e), nil
}

func (e *OrganizationPlansPlan) Scan(value any) error {
	switch x := value.(type) {
	case string:
		*e = OrganizationPlansPlan(x)
	case []byte:
		*e = OrganizationPlansPlan(x)
	case nil:
		return fmt.Errorf("cannot nil into OrganizationPlansPlan")
	default:
		return fmt.Errorf("cannot scan type %T: %v", value, value)
	}

	if !e.Valid() {
		return fmt.Errorf("invalid OrganizationPlansPlan value: %s", *e)
	}

	return nil
}

// Enum values for OrganizationsRole
const (
	OrganizationsRoleRL1 OrganizationsRole = "RL_1"
	OrganizationsRoleRL2 OrganizationsRole = "RL_2"
)

func AllOrganizationsRole() []OrganizationsRole {
	return []OrganizationsRole{
		OrganizationsRoleRL1,
		OrganizationsRoleRL2,
	}
}

type OrganizationsRole string

func (e OrganizationsRole) String() string {
	return string(e)
}

func (e OrganizationsRole) Valid() bool {
	switch e {
	case OrganizationsRoleRL1,
		OrganizationsRoleRL2:
		return true
	default:
		return false
	}
}

// useful when testing in other packages
func (e OrganizationsRole) All() []OrganizationsRole {
	return AllOrganizationsRole()
}

func (e OrganizationsRole) MarshalText() ([]byte, error) {
	return []byte(e), nil
}

func (e *OrganizationsRole) UnmarshalText(text []byte) error {
	return e.Scan(text)
}

func (e OrganizationsRole) MarshalBinary() ([]byte, error) {
	return []byte(e), nil
}

func (e *OrganizationsRole) UnmarshalBinary(data []byte) error {
	return e.Scan(data)
}

func (e OrganizationsRole) Value() (driver.Value, error) {
	return string(e), nil
}

func (e *OrganizationsRole) Scan(value any) error {
	switch x := value.(type) {
	case string:
		*e = OrganizationsRole(x)
	case []byte:
		*e = OrganizationsRole(x)
	case nil:
		return fmt.Errorf("cannot nil into OrganizationsRole")
	default:
		return fmt.Errorf("cannot scan type %T: %v", value, value)
	}

	if !e.Valid() {
		return fmt.Errorf("invalid OrganizationsRole value: %s", *e)
	}

	return nil
}
