// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	enums "github.com/eiicon-company/bobo/enums"
	models "github.com/eiicon-company/bobo/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type BannerMod interface {
	Apply(context.Context, *BannerTemplate)
}

type BannerModFunc func(context.Context, *BannerTemplate)

func (f BannerModFunc) Apply(ctx context.Context, n *BannerTemplate) {
	f(ctx, n)
}

type BannerModSlice []BannerMod

func (mods BannerModSlice) Apply(ctx context.Context, n *BannerTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// BannerTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type BannerTemplate struct {
	ID        func() int32
	Name      func() string
	State     func() enums.BannersState
	Sort      func() int32
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the BannerTemplate
func (o *BannerTemplate) Apply(ctx context.Context, mods ...BannerMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Banner
// according to the relationships in the template. Nothing is inserted into the db
func (t BannerTemplate) setModelRels(o *models.Banner) {}

// BuildSetter returns an *models.BannerSetter
// this does nothing with the relationship templates
func (o BannerTemplate) BuildSetter() *models.BannerSetter {
	m := &models.BannerSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.State != nil {
		val := o.State()
		m.State = omit.From(val)
	}
	if o.Sort != nil {
		val := o.Sort()
		m.Sort = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.BannerSetter
// this does nothing with the relationship templates
func (o BannerTemplate) BuildManySetter(number int) []*models.BannerSetter {
	m := make([]*models.BannerSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Banner
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use BannerTemplate.Create
func (o BannerTemplate) Build() *models.Banner {
	m := &models.Banner{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.State != nil {
		m.State = o.State()
	}
	if o.Sort != nil {
		m.Sort = o.Sort()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.BannerSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use BannerTemplate.CreateMany
func (o BannerTemplate) BuildMany(number int) models.BannerSlice {
	m := make(models.BannerSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableBanner(m *models.BannerSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "255")
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Banner
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *BannerTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Banner) error {
	var err error

	return err
}

// Create builds a banner and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *BannerTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Banner, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableBanner(opt)

	m, err := models.Banners.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a banner and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *BannerTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Banner {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a banner and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *BannerTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Banner {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple banners and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o BannerTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.BannerSlice, error) {
	var err error
	m := make(models.BannerSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple banners and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o BannerTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.BannerSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple banners and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o BannerTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.BannerSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Banner has methods that act as mods for the BannerTemplate
var BannerMods bannerMods

type bannerMods struct{}

func (m bannerMods) RandomizeAllColumns(f *faker.Faker) BannerMod {
	return BannerModSlice{
		BannerMods.RandomID(f),
		BannerMods.RandomName(f),
		BannerMods.RandomState(f),
		BannerMods.RandomSort(f),
		BannerMods.RandomCreatedAt(f),
		BannerMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m bannerMods) ID(val int32) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m bannerMods) IDFunc(f func() int32) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m bannerMods) UnsetID() BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bannerMods) RandomID(f *faker.Faker) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m bannerMods) Name(val string) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m bannerMods) NameFunc(f func() string) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m bannerMods) UnsetName() BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bannerMods) RandomName(f *faker.Faker) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m bannerMods) State(val enums.BannersState) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.State = func() enums.BannersState { return val }
	})
}

// Set the Column from the function
func (m bannerMods) StateFunc(f func() enums.BannersState) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.State = f
	})
}

// Clear any values for the column
func (m bannerMods) UnsetState() BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.State = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bannerMods) RandomState(f *faker.Faker) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.State = func() enums.BannersState {
			return random_enums_BannersState(f)
		}
	})
}

// Set the model columns to this value
func (m bannerMods) Sort(val int32) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Sort = func() int32 { return val }
	})
}

// Set the Column from the function
func (m bannerMods) SortFunc(f func() int32) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Sort = f
	})
}

// Clear any values for the column
func (m bannerMods) UnsetSort() BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Sort = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bannerMods) RandomSort(f *faker.Faker) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.Sort = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m bannerMods) CreatedAt(val time.Time) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m bannerMods) CreatedAtFunc(f func() time.Time) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m bannerMods) UnsetCreatedAt() BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bannerMods) RandomCreatedAt(f *faker.Faker) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

// Set the model columns to this value
func (m bannerMods) UpdatedAt(val time.Time) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m bannerMods) UpdatedAtFunc(f func() time.Time) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m bannerMods) UnsetUpdatedAt() BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bannerMods) RandomUpdatedAt(f *faker.Faker) BannerMod {
	return BannerModFunc(func(_ context.Context, o *BannerTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

func (m bannerMods) WithParentsCascading() BannerMod {
	return BannerModFunc(func(ctx context.Context, o *BannerTemplate) {
		if isDone, _ := bannerWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = bannerWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
