// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	enums "github.com/eiicon-company/bobo/enums"
	models "github.com/eiicon-company/bobo/models"
)

type Factory struct {
	baseBannerMods                BannerModSlice
	baseOrganizationPlanBuyerMods OrganizationPlanBuyerModSlice
	baseOrganizationPlanMods      OrganizationPlanModSlice
	baseOrganizationMods          OrganizationModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewBanner(mods ...BannerMod) *BannerTemplate {
	return f.NewBannerWithContext(context.Background(), mods...)
}

func (f *Factory) NewBannerWithContext(ctx context.Context, mods ...BannerMod) *BannerTemplate {
	o := &BannerTemplate{f: f}

	if f != nil {
		f.baseBannerMods.Apply(ctx, o)
	}

	BannerModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingBanner(m *models.Banner) *BannerTemplate {
	o := &BannerTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Name = func() string { return m.Name }
	o.State = func() enums.BannersState { return m.State }
	o.Sort = func() int32 { return m.Sort }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) NewOrganizationPlanBuyer(mods ...OrganizationPlanBuyerMod) *OrganizationPlanBuyerTemplate {
	return f.NewOrganizationPlanBuyerWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrganizationPlanBuyerWithContext(ctx context.Context, mods ...OrganizationPlanBuyerMod) *OrganizationPlanBuyerTemplate {
	o := &OrganizationPlanBuyerTemplate{f: f}

	if f != nil {
		f.baseOrganizationPlanBuyerMods.Apply(ctx, o)
	}

	OrganizationPlanBuyerModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrganizationPlanBuyer(m *models.OrganizationPlanBuyer) *OrganizationPlanBuyerTemplate {
	o := &OrganizationPlanBuyerTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.CompanyName = func() string { return m.CompanyName }
	o.PhoneNumber = func() string { return m.PhoneNumber }
	o.Email = func() string { return m.Email }
	o.Representative = func() string { return m.Representative }
	o.UserName = func() string { return m.UserName }
	o.Postcode = func() string { return m.Postcode }
	o.Address1 = func() string { return m.Address1 }
	o.Address2 = func() string { return m.Address2 }
	o.InvoicePostcode = func() string { return m.InvoicePostcode }
	o.InvoiceAddress1 = func() string { return m.InvoiceAddress1 }
	o.InvoiceAddress2 = func() string { return m.InvoiceAddress2 }
	o.InvoiceUserName = func() string { return m.InvoiceUserName }
	o.InvoiceEmail = func() string { return m.InvoiceEmail }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.OrganizationPlans) > 0 {
		OrganizationPlanBuyerMods.AddExistingOrganizationPlans(m.R.OrganizationPlans...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewOrganizationPlan(mods ...OrganizationPlanMod) *OrganizationPlanTemplate {
	return f.NewOrganizationPlanWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrganizationPlanWithContext(ctx context.Context, mods ...OrganizationPlanMod) *OrganizationPlanTemplate {
	o := &OrganizationPlanTemplate{f: f}

	if f != nil {
		f.baseOrganizationPlanMods.Apply(ctx, o)
	}

	OrganizationPlanModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrganizationPlan(m *models.OrganizationPlan) *OrganizationPlanTemplate {
	o := &OrganizationPlanTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.OrganizationID = func() int32 { return m.OrganizationID }
	o.OrganizationPlanBuyerID = func() int32 { return m.OrganizationPlanBuyerID }
	o.Plan = func() enums.OrganizationPlansPlan { return m.Plan }
	o.PaymentMethod = func() enums.OrganizationPlansPaymentMethod { return m.PaymentMethod }
	o.StripeCustomer = func() string { return m.StripeCustomer }
	o.StripeSubscription = func() string { return m.StripeSubscription }
	o.StripeCharge = func() string { return m.StripeCharge }
	o.UnsubscribedReason = func() string { return m.UnsubscribedReason }
	o.UnsubscribedRequestedAt = func() null.Val[time.Time] { return m.UnsubscribedRequestedAt }
	o.UnsubscribedActuallyAt = func() null.Val[time.Time] { return m.UnsubscribedActuallyAt }
	o.IsPending = func() bool { return m.IsPending }
	o.IsEnabled = func() null.Val[bool] { return m.IsEnabled }
	o.ContractPrice = func() int32 { return m.ContractPrice }
	o.ContractVersion = func() int32 { return m.ContractVersion }
	o.ContractPeriod = func() int32 { return m.ContractPeriod }
	o.ContractUpdatedAt = func() null.Val[time.Time] { return m.ContractUpdatedAt }
	o.ContractStartedAt = func() null.Val[time.Time] { return m.ContractStartedAt }
	o.ContractExpiredAt = func() time.Time { return m.ContractExpiredAt }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.Organization != nil {
		OrganizationPlanMods.WithExistingOrganization(m.R.Organization).Apply(ctx, o)
	}
	if m.R.OrganizationPlanBuyer != nil {
		OrganizationPlanMods.WithExistingOrganizationPlanBuyer(m.R.OrganizationPlanBuyer).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewOrganization(mods ...OrganizationMod) *OrganizationTemplate {
	return f.NewOrganizationWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrganizationWithContext(ctx context.Context, mods ...OrganizationMod) *OrganizationTemplate {
	o := &OrganizationTemplate{f: f}

	if f != nil {
		f.baseOrganizationMods.Apply(ctx, o)
	}

	OrganizationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrganization(m *models.Organization) *OrganizationTemplate {
	o := &OrganizationTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Identifier = func() string { return m.Identifier }
	o.Role = func() enums.OrganizationsRole { return m.Role }
	o.IsAuthed = func() bool { return m.IsAuthed }
	o.IsDeleted = func() bool { return m.IsDeleted }
	o.DeletedAt = func() null.Val[time.Time] { return m.DeletedAt }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.OrganizationPlans) > 0 {
		OrganizationMods.AddExistingOrganizationPlans(m.R.OrganizationPlans...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseBannerMods() {
	f.baseBannerMods = nil
}

func (f *Factory) AddBaseBannerMod(mods ...BannerMod) {
	f.baseBannerMods = append(f.baseBannerMods, mods...)
}

func (f *Factory) ClearBaseOrganizationPlanBuyerMods() {
	f.baseOrganizationPlanBuyerMods = nil
}

func (f *Factory) AddBaseOrganizationPlanBuyerMod(mods ...OrganizationPlanBuyerMod) {
	f.baseOrganizationPlanBuyerMods = append(f.baseOrganizationPlanBuyerMods, mods...)
}

func (f *Factory) ClearBaseOrganizationPlanMods() {
	f.baseOrganizationPlanMods = nil
}

func (f *Factory) AddBaseOrganizationPlanMod(mods ...OrganizationPlanMod) {
	f.baseOrganizationPlanMods = append(f.baseOrganizationPlanMods, mods...)
}

func (f *Factory) ClearBaseOrganizationMods() {
	f.baseOrganizationMods = nil
}

func (f *Factory) AddBaseOrganizationMod(mods ...OrganizationMod) {
	f.baseOrganizationMods = append(f.baseOrganizationMods, mods...)
}
