// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for banners
	bannerWithParentsCascadingCtx = newContextual[bool]("bannerWithParentsCascading")

	// Relationship Contexts for organization_plan_buyers
	organizationPlanBuyerWithParentsCascadingCtx = newContextual[bool]("organizationPlanBuyerWithParentsCascading")
	organizationPlanBuyerRelOrganizationPlansCtx = newContextual[bool]("organization_plan_buyers.organization_plans.fk_organization_plans_organization_plan_buyer_id")

	// Relationship Contexts for organization_plans
	organizationPlanWithParentsCascadingCtx     = newContextual[bool]("organizationPlanWithParentsCascading")
	organizationPlanRelOrganizationCtx          = newContextual[bool]("organization_plans.organizations.fk_organization_plans_organization_id")
	organizationPlanRelOrganizationPlanBuyerCtx = newContextual[bool]("organization_plan_buyers.organization_plans.fk_organization_plans_organization_plan_buyer_id")

	// Relationship Contexts for organizations
	organizationWithParentsCascadingCtx = newContextual[bool]("organizationWithParentsCascading")
	organizationRelOrganizationPlansCtx = newContextual[bool]("organization_plans.organizations.fk_organization_plans_organization_id")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
