// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	enums "github.com/eiicon-company/bobo/enums"
	models "github.com/eiicon-company/bobo/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type OrganizationMod interface {
	Apply(context.Context, *OrganizationTemplate)
}

type OrganizationModFunc func(context.Context, *OrganizationTemplate)

func (f OrganizationModFunc) Apply(ctx context.Context, n *OrganizationTemplate) {
	f(ctx, n)
}

type OrganizationModSlice []OrganizationMod

func (mods OrganizationModSlice) Apply(ctx context.Context, n *OrganizationTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrganizationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrganizationTemplate struct {
	ID         func() int32
	Identifier func() string
	Role       func() enums.OrganizationsRole
	IsAuthed   func() bool
	IsDeleted  func() bool
	DeletedAt  func() null.Val[time.Time]
	CreatedAt  func() time.Time
	UpdatedAt  func() time.Time

	r organizationR
	f *Factory

	alreadyPersisted bool
}

type organizationR struct {
	OrganizationPlans []*organizationROrganizationPlansR
}

type organizationROrganizationPlansR struct {
	number int
	o      *OrganizationPlanTemplate
}

// Apply mods to the OrganizationTemplate
func (o *OrganizationTemplate) Apply(ctx context.Context, mods ...OrganizationMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Organization
// according to the relationships in the template. Nothing is inserted into the db
func (t OrganizationTemplate) setModelRels(o *models.Organization) {
	if t.r.OrganizationPlans != nil {
		rel := models.OrganizationPlanSlice{}
		for _, r := range t.r.OrganizationPlans {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OrganizationID = o.ID // h2
				rel.R.Organization = o
			}
			rel = append(rel, related...)
		}
		o.R.OrganizationPlans = rel
	}
}

// BuildSetter returns an *models.OrganizationSetter
// this does nothing with the relationship templates
func (o OrganizationTemplate) BuildSetter() *models.OrganizationSetter {
	m := &models.OrganizationSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Identifier != nil {
		val := o.Identifier()
		m.Identifier = omit.From(val)
	}
	if o.Role != nil {
		val := o.Role()
		m.Role = omit.From(val)
	}
	if o.IsAuthed != nil {
		val := o.IsAuthed()
		m.IsAuthed = omit.From(val)
	}
	if o.IsDeleted != nil {
		val := o.IsDeleted()
		m.IsDeleted = omit.From(val)
	}
	if o.DeletedAt != nil {
		val := o.DeletedAt()
		m.DeletedAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrganizationSetter
// this does nothing with the relationship templates
func (o OrganizationTemplate) BuildManySetter(number int) []*models.OrganizationSetter {
	m := make([]*models.OrganizationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Organization
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationTemplate.Create
func (o OrganizationTemplate) Build() *models.Organization {
	m := &models.Organization{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Identifier != nil {
		m.Identifier = o.Identifier()
	}
	if o.Role != nil {
		m.Role = o.Role()
	}
	if o.IsAuthed != nil {
		m.IsAuthed = o.IsAuthed()
	}
	if o.IsDeleted != nil {
		m.IsDeleted = o.IsDeleted()
	}
	if o.DeletedAt != nil {
		m.DeletedAt = o.DeletedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrganizationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationTemplate.CreateMany
func (o OrganizationTemplate) BuildMany(number int) models.OrganizationSlice {
	m := make(models.OrganizationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrganization(m *models.OrganizationSetter) {
	if !(m.Identifier.IsValue()) {
		val := random_string(nil, "255")
		m.Identifier = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Organization
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrganizationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Organization) error {
	var err error

	isOrganizationPlansDone, _ := organizationRelOrganizationPlansCtx.Value(ctx)
	if !isOrganizationPlansDone && o.r.OrganizationPlans != nil {
		ctx = organizationRelOrganizationPlansCtx.WithValue(ctx, true)
		for _, r := range o.r.OrganizationPlans {
			if r.o.alreadyPersisted {
				m.R.OrganizationPlans = append(m.R.OrganizationPlans, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrganizationPlans(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a organization and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrganizationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Organization, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrganization(opt)

	m, err := models.Organizations.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a organization and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrganizationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Organization {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a organization and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrganizationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Organization {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple organizations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrganizationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrganizationSlice, error) {
	var err error
	m := make(models.OrganizationSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple organizations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrganizationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrganizationSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple organizations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrganizationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrganizationSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Organization has methods that act as mods for the OrganizationTemplate
var OrganizationMods organizationMods

type organizationMods struct{}

func (m organizationMods) RandomizeAllColumns(f *faker.Faker) OrganizationMod {
	return OrganizationModSlice{
		OrganizationMods.RandomID(f),
		OrganizationMods.RandomIdentifier(f),
		OrganizationMods.RandomRole(f),
		OrganizationMods.RandomIsAuthed(f),
		OrganizationMods.RandomIsDeleted(f),
		OrganizationMods.RandomDeletedAt(f),
		OrganizationMods.RandomCreatedAt(f),
		OrganizationMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m organizationMods) ID(val int32) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationMods) IDFunc(f func() int32) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetID() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomID(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Identifier(val string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Identifier = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationMods) IdentifierFunc(f func() string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Identifier = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetIdentifier() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Identifier = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomIdentifier(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Identifier = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Role(val enums.OrganizationsRole) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Role = func() enums.OrganizationsRole { return val }
	})
}

// Set the Column from the function
func (m organizationMods) RoleFunc(f func() enums.OrganizationsRole) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Role = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetRole() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Role = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomRole(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Role = func() enums.OrganizationsRole {
			return random_enums_OrganizationsRole(f)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) IsAuthed(val bool) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsAuthed = func() bool { return val }
	})
}

// Set the Column from the function
func (m organizationMods) IsAuthedFunc(f func() bool) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsAuthed = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetIsAuthed() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsAuthed = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomIsAuthed(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsAuthed = func() bool {
			return random_bool(f, "1")
		}
	})
}

// Set the model columns to this value
func (m organizationMods) IsDeleted(val bool) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsDeleted = func() bool { return val }
	})
}

// Set the Column from the function
func (m organizationMods) IsDeletedFunc(f func() bool) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsDeleted = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetIsDeleted() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsDeleted = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomIsDeleted(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.IsDeleted = func() bool {
			return random_bool(f, "1")
		}
	})
}

// Set the model columns to this value
func (m organizationMods) DeletedAt(val null.Val[time.Time]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.DeletedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) DeletedAtFunc(f func() null.Val[time.Time]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.DeletedAt = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetDeletedAt() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.DeletedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomDeletedAt(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.DeletedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomDeletedAtNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.DeletedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) CreatedAt(val time.Time) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationMods) CreatedAtFunc(f func() time.Time) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetCreatedAt() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomCreatedAt(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

// Set the model columns to this value
func (m organizationMods) UpdatedAt(val time.Time) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationMods) UpdatedAtFunc(f func() time.Time) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetUpdatedAt() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomUpdatedAt(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

func (m organizationMods) WithParentsCascading() OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		if isDone, _ := organizationWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = organizationWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m organizationMods) WithOrganizationPlans(number int, related *OrganizationPlanTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationPlans = []*organizationROrganizationPlansR{{
			number: number,
			o:      related,
		}}
	})
}

func (m organizationMods) WithNewOrganizationPlans(number int, mods ...OrganizationPlanMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewOrganizationPlanWithContext(ctx, mods...)
		m.WithOrganizationPlans(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddOrganizationPlans(number int, related *OrganizationPlanTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationPlans = append(o.r.OrganizationPlans, &organizationROrganizationPlansR{
			number: number,
			o:      related,
		})
	})
}

func (m organizationMods) AddNewOrganizationPlans(number int, mods ...OrganizationPlanMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewOrganizationPlanWithContext(ctx, mods...)
		m.AddOrganizationPlans(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddExistingOrganizationPlans(existingModels ...*models.OrganizationPlan) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		for _, em := range existingModels {
			o.r.OrganizationPlans = append(o.r.OrganizationPlans, &organizationROrganizationPlansR{
				o: o.f.FromExistingOrganizationPlan(em),
			})
		}
	})
}

func (m organizationMods) WithoutOrganizationPlans() OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationPlans = nil
	})
}
