// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	enums "github.com/eiicon-company/bobo/enums"
	models "github.com/eiicon-company/bobo/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type OrganizationPlanMod interface {
	Apply(context.Context, *OrganizationPlanTemplate)
}

type OrganizationPlanModFunc func(context.Context, *OrganizationPlanTemplate)

func (f OrganizationPlanModFunc) Apply(ctx context.Context, n *OrganizationPlanTemplate) {
	f(ctx, n)
}

type OrganizationPlanModSlice []OrganizationPlanMod

func (mods OrganizationPlanModSlice) Apply(ctx context.Context, n *OrganizationPlanTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrganizationPlanTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrganizationPlanTemplate struct {
	ID                      func() int32
	OrganizationID          func() int32
	OrganizationPlanBuyerID func() int32
	Plan                    func() enums.OrganizationPlansPlan
	PaymentMethod           func() enums.OrganizationPlansPaymentMethod
	StripeCustomer          func() string
	StripeSubscription      func() string
	StripeCharge            func() string
	UnsubscribedReason      func() string
	UnsubscribedRequestedAt func() null.Val[time.Time]
	UnsubscribedActuallyAt  func() null.Val[time.Time]
	IsPending               func() bool
	IsEnabled               func() null.Val[bool]
	ContractPrice           func() int32
	ContractVersion         func() int32
	ContractPeriod          func() int32
	ContractUpdatedAt       func() null.Val[time.Time]
	ContractStartedAt       func() null.Val[time.Time]
	ContractExpiredAt       func() time.Time
	CreatedAt               func() time.Time
	UpdatedAt               func() time.Time

	r organizationPlanR
	f *Factory

	alreadyPersisted bool
}

type organizationPlanR struct {
	Organization          *organizationPlanROrganizationR
	OrganizationPlanBuyer *organizationPlanROrganizationPlanBuyerR
}

type organizationPlanROrganizationR struct {
	o *OrganizationTemplate
}
type organizationPlanROrganizationPlanBuyerR struct {
	o *OrganizationPlanBuyerTemplate
}

// Apply mods to the OrganizationPlanTemplate
func (o *OrganizationPlanTemplate) Apply(ctx context.Context, mods ...OrganizationPlanMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.OrganizationPlan
// according to the relationships in the template. Nothing is inserted into the db
func (t OrganizationPlanTemplate) setModelRels(o *models.OrganizationPlan) {
	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.OrganizationPlans = append(rel.R.OrganizationPlans, o)
		o.OrganizationID = rel.ID // h2
		o.R.Organization = rel
	}

	if t.r.OrganizationPlanBuyer != nil {
		rel := t.r.OrganizationPlanBuyer.o.Build()
		rel.R.OrganizationPlans = append(rel.R.OrganizationPlans, o)
		o.OrganizationPlanBuyerID = rel.ID // h2
		o.R.OrganizationPlanBuyer = rel
	}
}

// BuildSetter returns an *models.OrganizationPlanSetter
// this does nothing with the relationship templates
func (o OrganizationPlanTemplate) BuildSetter() *models.OrganizationPlanSetter {
	m := &models.OrganizationPlanSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omit.From(val)
	}
	if o.OrganizationPlanBuyerID != nil {
		val := o.OrganizationPlanBuyerID()
		m.OrganizationPlanBuyerID = omit.From(val)
	}
	if o.Plan != nil {
		val := o.Plan()
		m.Plan = omit.From(val)
	}
	if o.PaymentMethod != nil {
		val := o.PaymentMethod()
		m.PaymentMethod = omit.From(val)
	}
	if o.StripeCustomer != nil {
		val := o.StripeCustomer()
		m.StripeCustomer = omit.From(val)
	}
	if o.StripeSubscription != nil {
		val := o.StripeSubscription()
		m.StripeSubscription = omit.From(val)
	}
	if o.StripeCharge != nil {
		val := o.StripeCharge()
		m.StripeCharge = omit.From(val)
	}
	if o.UnsubscribedReason != nil {
		val := o.UnsubscribedReason()
		m.UnsubscribedReason = omit.From(val)
	}
	if o.UnsubscribedRequestedAt != nil {
		val := o.UnsubscribedRequestedAt()
		m.UnsubscribedRequestedAt = omitnull.FromNull(val)
	}
	if o.UnsubscribedActuallyAt != nil {
		val := o.UnsubscribedActuallyAt()
		m.UnsubscribedActuallyAt = omitnull.FromNull(val)
	}
	if o.IsPending != nil {
		val := o.IsPending()
		m.IsPending = omit.From(val)
	}
	if o.IsEnabled != nil {
		val := o.IsEnabled()
		m.IsEnabled = omitnull.FromNull(val)
	}
	if o.ContractPrice != nil {
		val := o.ContractPrice()
		m.ContractPrice = omit.From(val)
	}
	if o.ContractVersion != nil {
		val := o.ContractVersion()
		m.ContractVersion = omit.From(val)
	}
	if o.ContractPeriod != nil {
		val := o.ContractPeriod()
		m.ContractPeriod = omit.From(val)
	}
	if o.ContractUpdatedAt != nil {
		val := o.ContractUpdatedAt()
		m.ContractUpdatedAt = omitnull.FromNull(val)
	}
	if o.ContractStartedAt != nil {
		val := o.ContractStartedAt()
		m.ContractStartedAt = omitnull.FromNull(val)
	}
	if o.ContractExpiredAt != nil {
		val := o.ContractExpiredAt()
		m.ContractExpiredAt = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrganizationPlanSetter
// this does nothing with the relationship templates
func (o OrganizationPlanTemplate) BuildManySetter(number int) []*models.OrganizationPlanSetter {
	m := make([]*models.OrganizationPlanSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.OrganizationPlan
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationPlanTemplate.Create
func (o OrganizationPlanTemplate) Build() *models.OrganizationPlan {
	m := &models.OrganizationPlan{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.OrganizationPlanBuyerID != nil {
		m.OrganizationPlanBuyerID = o.OrganizationPlanBuyerID()
	}
	if o.Plan != nil {
		m.Plan = o.Plan()
	}
	if o.PaymentMethod != nil {
		m.PaymentMethod = o.PaymentMethod()
	}
	if o.StripeCustomer != nil {
		m.StripeCustomer = o.StripeCustomer()
	}
	if o.StripeSubscription != nil {
		m.StripeSubscription = o.StripeSubscription()
	}
	if o.StripeCharge != nil {
		m.StripeCharge = o.StripeCharge()
	}
	if o.UnsubscribedReason != nil {
		m.UnsubscribedReason = o.UnsubscribedReason()
	}
	if o.UnsubscribedRequestedAt != nil {
		m.UnsubscribedRequestedAt = o.UnsubscribedRequestedAt()
	}
	if o.UnsubscribedActuallyAt != nil {
		m.UnsubscribedActuallyAt = o.UnsubscribedActuallyAt()
	}
	if o.IsPending != nil {
		m.IsPending = o.IsPending()
	}
	if o.IsEnabled != nil {
		m.IsEnabled = o.IsEnabled()
	}
	if o.ContractPrice != nil {
		m.ContractPrice = o.ContractPrice()
	}
	if o.ContractVersion != nil {
		m.ContractVersion = o.ContractVersion()
	}
	if o.ContractPeriod != nil {
		m.ContractPeriod = o.ContractPeriod()
	}
	if o.ContractUpdatedAt != nil {
		m.ContractUpdatedAt = o.ContractUpdatedAt()
	}
	if o.ContractStartedAt != nil {
		m.ContractStartedAt = o.ContractStartedAt()
	}
	if o.ContractExpiredAt != nil {
		m.ContractExpiredAt = o.ContractExpiredAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrganizationPlanSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationPlanTemplate.CreateMany
func (o OrganizationPlanTemplate) BuildMany(number int) models.OrganizationPlanSlice {
	m := make(models.OrganizationPlanSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrganizationPlan(m *models.OrganizationPlanSetter) {
	if !(m.OrganizationID.IsValue()) {
		val := random_int32(nil)
		m.OrganizationID = omit.From(val)
	}
	if !(m.OrganizationPlanBuyerID.IsValue()) {
		val := random_int32(nil)
		m.OrganizationPlanBuyerID = omit.From(val)
	}
	if !(m.StripeCustomer.IsValue()) {
		val := random_string(nil, "255")
		m.StripeCustomer = omit.From(val)
	}
	if !(m.StripeSubscription.IsValue()) {
		val := random_string(nil, "255")
		m.StripeSubscription = omit.From(val)
	}
	if !(m.StripeCharge.IsValue()) {
		val := random_string(nil, "255")
		m.StripeCharge = omit.From(val)
	}
	if !(m.UnsubscribedReason.IsValue()) {
		val := random_string(nil, "2048")
		m.UnsubscribedReason = omit.From(val)
	}
	if !(m.ContractVersion.IsValue()) {
		val := random_int32(nil)
		m.ContractVersion = omit.From(val)
	}
	if !(m.ContractPeriod.IsValue()) {
		val := random_int32(nil)
		m.ContractPeriod = omit.From(val)
	}
	if !(m.ContractExpiredAt.IsValue()) {
		val := random_time_Time(nil, "6")
		m.ContractExpiredAt = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.OrganizationPlan
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrganizationPlanTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.OrganizationPlan) error {
	var err error

	return err
}

// Create builds a organizationPlan and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrganizationPlanTemplate) Create(ctx context.Context, exec bob.Executor) (*models.OrganizationPlan, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrganizationPlan(opt)

	if o.r.Organization == nil {
		OrganizationPlanMods.WithNewOrganization().Apply(ctx, o)
	}

	var rel0 *models.Organization

	if o.r.Organization.o.alreadyPersisted {
		rel0 = o.r.Organization.o.Build()
	} else {
		rel0, err = o.r.Organization.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationID = omit.From(rel0.ID)

	if o.r.OrganizationPlanBuyer == nil {
		OrganizationPlanMods.WithNewOrganizationPlanBuyer().Apply(ctx, o)
	}

	var rel1 *models.OrganizationPlanBuyer

	if o.r.OrganizationPlanBuyer.o.alreadyPersisted {
		rel1 = o.r.OrganizationPlanBuyer.o.Build()
	} else {
		rel1, err = o.r.OrganizationPlanBuyer.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationPlanBuyerID = omit.From(rel1.ID)

	m, err := models.OrganizationPlans.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Organization = rel0
	m.R.OrganizationPlanBuyer = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a organizationPlan and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrganizationPlanTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.OrganizationPlan {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a organizationPlan and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrganizationPlanTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.OrganizationPlan {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple organizationPlans and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrganizationPlanTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrganizationPlanSlice, error) {
	var err error
	m := make(models.OrganizationPlanSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple organizationPlans and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrganizationPlanTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrganizationPlanSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple organizationPlans and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrganizationPlanTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrganizationPlanSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// OrganizationPlan has methods that act as mods for the OrganizationPlanTemplate
var OrganizationPlanMods organizationPlanMods

type organizationPlanMods struct{}

func (m organizationPlanMods) RandomizeAllColumns(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModSlice{
		OrganizationPlanMods.RandomID(f),
		OrganizationPlanMods.RandomOrganizationID(f),
		OrganizationPlanMods.RandomOrganizationPlanBuyerID(f),
		OrganizationPlanMods.RandomPlan(f),
		OrganizationPlanMods.RandomPaymentMethod(f),
		OrganizationPlanMods.RandomStripeCustomer(f),
		OrganizationPlanMods.RandomStripeSubscription(f),
		OrganizationPlanMods.RandomStripeCharge(f),
		OrganizationPlanMods.RandomUnsubscribedReason(f),
		OrganizationPlanMods.RandomUnsubscribedRequestedAt(f),
		OrganizationPlanMods.RandomUnsubscribedActuallyAt(f),
		OrganizationPlanMods.RandomIsPending(f),
		OrganizationPlanMods.RandomIsEnabled(f),
		OrganizationPlanMods.RandomContractPrice(f),
		OrganizationPlanMods.RandomContractVersion(f),
		OrganizationPlanMods.RandomContractPeriod(f),
		OrganizationPlanMods.RandomContractUpdatedAt(f),
		OrganizationPlanMods.RandomContractStartedAt(f),
		OrganizationPlanMods.RandomContractExpiredAt(f),
		OrganizationPlanMods.RandomCreatedAt(f),
		OrganizationPlanMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m organizationPlanMods) ID(val int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) IDFunc(f func() int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetID() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomID(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) OrganizationID(val int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) OrganizationIDFunc(f func() int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetOrganizationID() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomOrganizationID(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) OrganizationPlanBuyerID(val int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationPlanBuyerID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) OrganizationPlanBuyerIDFunc(f func() int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationPlanBuyerID = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetOrganizationPlanBuyerID() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationPlanBuyerID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomOrganizationPlanBuyerID(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.OrganizationPlanBuyerID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) Plan(val enums.OrganizationPlansPlan) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.Plan = func() enums.OrganizationPlansPlan { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) PlanFunc(f func() enums.OrganizationPlansPlan) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.Plan = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetPlan() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.Plan = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomPlan(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.Plan = func() enums.OrganizationPlansPlan {
			return random_enums_OrganizationPlansPlan(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) PaymentMethod(val enums.OrganizationPlansPaymentMethod) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.PaymentMethod = func() enums.OrganizationPlansPaymentMethod { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) PaymentMethodFunc(f func() enums.OrganizationPlansPaymentMethod) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.PaymentMethod = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetPaymentMethod() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.PaymentMethod = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomPaymentMethod(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.PaymentMethod = func() enums.OrganizationPlansPaymentMethod {
			return random_enums_OrganizationPlansPaymentMethod(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) StripeCustomer(val string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCustomer = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) StripeCustomerFunc(f func() string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCustomer = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetStripeCustomer() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCustomer = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomStripeCustomer(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCustomer = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) StripeSubscription(val string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeSubscription = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) StripeSubscriptionFunc(f func() string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeSubscription = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetStripeSubscription() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeSubscription = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomStripeSubscription(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeSubscription = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) StripeCharge(val string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCharge = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) StripeChargeFunc(f func() string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCharge = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetStripeCharge() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCharge = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomStripeCharge(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.StripeCharge = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) UnsubscribedReason(val string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedReason = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) UnsubscribedReasonFunc(f func() string) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedReason = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetUnsubscribedReason() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedReason = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomUnsubscribedReason(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedReason = func() string {
			return random_string(f, "2048")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) UnsubscribedRequestedAt(val null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedRequestedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) UnsubscribedRequestedAtFunc(f func() null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedRequestedAt = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetUnsubscribedRequestedAt() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedRequestedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPlanMods) RandomUnsubscribedRequestedAt(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedRequestedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPlanMods) RandomUnsubscribedRequestedAtNotNull(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedRequestedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) UnsubscribedActuallyAt(val null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedActuallyAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) UnsubscribedActuallyAtFunc(f func() null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedActuallyAt = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetUnsubscribedActuallyAt() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedActuallyAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPlanMods) RandomUnsubscribedActuallyAt(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedActuallyAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPlanMods) RandomUnsubscribedActuallyAtNotNull(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UnsubscribedActuallyAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) IsPending(val bool) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsPending = func() bool { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) IsPendingFunc(f func() bool) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsPending = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetIsPending() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsPending = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomIsPending(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsPending = func() bool {
			return random_bool(f, "1")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) IsEnabled(val null.Val[bool]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsEnabled = func() null.Val[bool] { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) IsEnabledFunc(f func() null.Val[bool]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsEnabled = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetIsEnabled() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsEnabled = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPlanMods) RandomIsEnabled(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsEnabled = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f, "1")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPlanMods) RandomIsEnabledNotNull(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.IsEnabled = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f, "1")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) ContractPrice(val int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPrice = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) ContractPriceFunc(f func() int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPrice = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetContractPrice() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPrice = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomContractPrice(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPrice = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) ContractVersion(val int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractVersion = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) ContractVersionFunc(f func() int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractVersion = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetContractVersion() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractVersion = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomContractVersion(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractVersion = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) ContractPeriod(val int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPeriod = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) ContractPeriodFunc(f func() int32) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPeriod = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetContractPeriod() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPeriod = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomContractPeriod(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractPeriod = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) ContractUpdatedAt(val null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractUpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) ContractUpdatedAtFunc(f func() null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractUpdatedAt = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetContractUpdatedAt() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractUpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPlanMods) RandomContractUpdatedAt(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractUpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPlanMods) RandomContractUpdatedAtNotNull(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractUpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) ContractStartedAt(val null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractStartedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) ContractStartedAtFunc(f func() null.Val[time.Time]) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractStartedAt = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetContractStartedAt() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractStartedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPlanMods) RandomContractStartedAt(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractStartedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPlanMods) RandomContractStartedAtNotNull(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractStartedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f, "6")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) ContractExpiredAt(val time.Time) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractExpiredAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) ContractExpiredAtFunc(f func() time.Time) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractExpiredAt = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetContractExpiredAt() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractExpiredAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomContractExpiredAt(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.ContractExpiredAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) CreatedAt(val time.Time) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) CreatedAtFunc(f func() time.Time) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetCreatedAt() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomCreatedAt(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanMods) UpdatedAt(val time.Time) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationPlanMods) UpdatedAtFunc(f func() time.Time) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m organizationPlanMods) UnsetUpdatedAt() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanMods) RandomUpdatedAt(f *faker.Faker) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(_ context.Context, o *OrganizationPlanTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

func (m organizationPlanMods) WithParentsCascading() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		if isDone, _ := organizationPlanWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = organizationPlanWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
		{

			related := o.f.NewOrganizationPlanBuyerWithContext(ctx, OrganizationPlanBuyerMods.WithParentsCascading())
			m.WithOrganizationPlanBuyer(related).Apply(ctx, o)
		}
	})
}

func (m organizationPlanMods) WithOrganization(rel *OrganizationTemplate) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		o.r.Organization = &organizationPlanROrganizationR{
			o: rel,
		}
	})
}

func (m organizationPlanMods) WithNewOrganization(mods ...OrganizationMod) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m organizationPlanMods) WithExistingOrganization(em *models.Organization) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		o.r.Organization = &organizationPlanROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m organizationPlanMods) WithoutOrganization() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		o.r.Organization = nil
	})
}

func (m organizationPlanMods) WithOrganizationPlanBuyer(rel *OrganizationPlanBuyerTemplate) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		o.r.OrganizationPlanBuyer = &organizationPlanROrganizationPlanBuyerR{
			o: rel,
		}
	})
}

func (m organizationPlanMods) WithNewOrganizationPlanBuyer(mods ...OrganizationPlanBuyerMod) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		related := o.f.NewOrganizationPlanBuyerWithContext(ctx, mods...)

		m.WithOrganizationPlanBuyer(related).Apply(ctx, o)
	})
}

func (m organizationPlanMods) WithExistingOrganizationPlanBuyer(em *models.OrganizationPlanBuyer) OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		o.r.OrganizationPlanBuyer = &organizationPlanROrganizationPlanBuyerR{
			o: o.f.FromExistingOrganizationPlanBuyer(em),
		}
	})
}

func (m organizationPlanMods) WithoutOrganizationPlanBuyer() OrganizationPlanMod {
	return OrganizationPlanModFunc(func(ctx context.Context, o *OrganizationPlanTemplate) {
		o.r.OrganizationPlanBuyer = nil
	})
}
