// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	models "github.com/eiicon-company/bobo/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type OrganizationPlanBuyerMod interface {
	Apply(context.Context, *OrganizationPlanBuyerTemplate)
}

type OrganizationPlanBuyerModFunc func(context.Context, *OrganizationPlanBuyerTemplate)

func (f OrganizationPlanBuyerModFunc) Apply(ctx context.Context, n *OrganizationPlanBuyerTemplate) {
	f(ctx, n)
}

type OrganizationPlanBuyerModSlice []OrganizationPlanBuyerMod

func (mods OrganizationPlanBuyerModSlice) Apply(ctx context.Context, n *OrganizationPlanBuyerTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrganizationPlanBuyerTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrganizationPlanBuyerTemplate struct {
	ID              func() int32
	CompanyName     func() string
	PhoneNumber     func() string
	Email           func() string
	Representative  func() string
	UserName        func() string
	Postcode        func() string
	Address1        func() string
	Address2        func() string
	InvoicePostcode func() string
	InvoiceAddress1 func() string
	InvoiceAddress2 func() string
	InvoiceUserName func() string
	InvoiceEmail    func() string
	CreatedAt       func() time.Time
	UpdatedAt       func() time.Time

	r organizationPlanBuyerR
	f *Factory

	alreadyPersisted bool
}

type organizationPlanBuyerR struct {
	OrganizationPlans []*organizationPlanBuyerROrganizationPlansR
}

type organizationPlanBuyerROrganizationPlansR struct {
	number int
	o      *OrganizationPlanTemplate
}

// Apply mods to the OrganizationPlanBuyerTemplate
func (o *OrganizationPlanBuyerTemplate) Apply(ctx context.Context, mods ...OrganizationPlanBuyerMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.OrganizationPlanBuyer
// according to the relationships in the template. Nothing is inserted into the db
func (t OrganizationPlanBuyerTemplate) setModelRels(o *models.OrganizationPlanBuyer) {
	if t.r.OrganizationPlans != nil {
		rel := models.OrganizationPlanSlice{}
		for _, r := range t.r.OrganizationPlans {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OrganizationPlanBuyerID = o.ID // h2
				rel.R.OrganizationPlanBuyer = o
			}
			rel = append(rel, related...)
		}
		o.R.OrganizationPlans = rel
	}
}

// BuildSetter returns an *models.OrganizationPlanBuyerSetter
// this does nothing with the relationship templates
func (o OrganizationPlanBuyerTemplate) BuildSetter() *models.OrganizationPlanBuyerSetter {
	m := &models.OrganizationPlanBuyerSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.CompanyName != nil {
		val := o.CompanyName()
		m.CompanyName = omit.From(val)
	}
	if o.PhoneNumber != nil {
		val := o.PhoneNumber()
		m.PhoneNumber = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Representative != nil {
		val := o.Representative()
		m.Representative = omit.From(val)
	}
	if o.UserName != nil {
		val := o.UserName()
		m.UserName = omit.From(val)
	}
	if o.Postcode != nil {
		val := o.Postcode()
		m.Postcode = omit.From(val)
	}
	if o.Address1 != nil {
		val := o.Address1()
		m.Address1 = omit.From(val)
	}
	if o.Address2 != nil {
		val := o.Address2()
		m.Address2 = omit.From(val)
	}
	if o.InvoicePostcode != nil {
		val := o.InvoicePostcode()
		m.InvoicePostcode = omit.From(val)
	}
	if o.InvoiceAddress1 != nil {
		val := o.InvoiceAddress1()
		m.InvoiceAddress1 = omit.From(val)
	}
	if o.InvoiceAddress2 != nil {
		val := o.InvoiceAddress2()
		m.InvoiceAddress2 = omit.From(val)
	}
	if o.InvoiceUserName != nil {
		val := o.InvoiceUserName()
		m.InvoiceUserName = omit.From(val)
	}
	if o.InvoiceEmail != nil {
		val := o.InvoiceEmail()
		m.InvoiceEmail = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrganizationPlanBuyerSetter
// this does nothing with the relationship templates
func (o OrganizationPlanBuyerTemplate) BuildManySetter(number int) []*models.OrganizationPlanBuyerSetter {
	m := make([]*models.OrganizationPlanBuyerSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.OrganizationPlanBuyer
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationPlanBuyerTemplate.Create
func (o OrganizationPlanBuyerTemplate) Build() *models.OrganizationPlanBuyer {
	m := &models.OrganizationPlanBuyer{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.CompanyName != nil {
		m.CompanyName = o.CompanyName()
	}
	if o.PhoneNumber != nil {
		m.PhoneNumber = o.PhoneNumber()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Representative != nil {
		m.Representative = o.Representative()
	}
	if o.UserName != nil {
		m.UserName = o.UserName()
	}
	if o.Postcode != nil {
		m.Postcode = o.Postcode()
	}
	if o.Address1 != nil {
		m.Address1 = o.Address1()
	}
	if o.Address2 != nil {
		m.Address2 = o.Address2()
	}
	if o.InvoicePostcode != nil {
		m.InvoicePostcode = o.InvoicePostcode()
	}
	if o.InvoiceAddress1 != nil {
		m.InvoiceAddress1 = o.InvoiceAddress1()
	}
	if o.InvoiceAddress2 != nil {
		m.InvoiceAddress2 = o.InvoiceAddress2()
	}
	if o.InvoiceUserName != nil {
		m.InvoiceUserName = o.InvoiceUserName()
	}
	if o.InvoiceEmail != nil {
		m.InvoiceEmail = o.InvoiceEmail()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrganizationPlanBuyerSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationPlanBuyerTemplate.CreateMany
func (o OrganizationPlanBuyerTemplate) BuildMany(number int) models.OrganizationPlanBuyerSlice {
	m := make(models.OrganizationPlanBuyerSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrganizationPlanBuyer(m *models.OrganizationPlanBuyerSetter) {
	if !(m.CompanyName.IsValue()) {
		val := random_string(nil, "255")
		m.CompanyName = omit.From(val)
	}
	if !(m.PhoneNumber.IsValue()) {
		val := random_string(nil, "128")
		m.PhoneNumber = omit.From(val)
	}
	if !(m.Email.IsValue()) {
		val := random_string(nil, "255")
		m.Email = omit.From(val)
	}
	if !(m.Representative.IsValue()) {
		val := random_string(nil, "255")
		m.Representative = omit.From(val)
	}
	if !(m.UserName.IsValue()) {
		val := random_string(nil, "255")
		m.UserName = omit.From(val)
	}
	if !(m.Postcode.IsValue()) {
		val := random_string(nil, "255")
		m.Postcode = omit.From(val)
	}
	if !(m.Address1.IsValue()) {
		val := random_string(nil, "255")
		m.Address1 = omit.From(val)
	}
	if !(m.Address2.IsValue()) {
		val := random_string(nil, "255")
		m.Address2 = omit.From(val)
	}
	if !(m.InvoicePostcode.IsValue()) {
		val := random_string(nil, "255")
		m.InvoicePostcode = omit.From(val)
	}
	if !(m.InvoiceAddress1.IsValue()) {
		val := random_string(nil, "255")
		m.InvoiceAddress1 = omit.From(val)
	}
	if !(m.InvoiceAddress2.IsValue()) {
		val := random_string(nil, "255")
		m.InvoiceAddress2 = omit.From(val)
	}
	if !(m.InvoiceUserName.IsValue()) {
		val := random_string(nil, "255")
		m.InvoiceUserName = omit.From(val)
	}
	if !(m.InvoiceEmail.IsValue()) {
		val := random_string(nil, "255")
		m.InvoiceEmail = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.OrganizationPlanBuyer
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrganizationPlanBuyerTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.OrganizationPlanBuyer) error {
	var err error

	isOrganizationPlansDone, _ := organizationPlanBuyerRelOrganizationPlansCtx.Value(ctx)
	if !isOrganizationPlansDone && o.r.OrganizationPlans != nil {
		ctx = organizationPlanBuyerRelOrganizationPlansCtx.WithValue(ctx, true)
		for _, r := range o.r.OrganizationPlans {
			if r.o.alreadyPersisted {
				m.R.OrganizationPlans = append(m.R.OrganizationPlans, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrganizationPlans(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a organizationPlanBuyer and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrganizationPlanBuyerTemplate) Create(ctx context.Context, exec bob.Executor) (*models.OrganizationPlanBuyer, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrganizationPlanBuyer(opt)

	m, err := models.OrganizationPlanBuyers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a organizationPlanBuyer and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrganizationPlanBuyerTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.OrganizationPlanBuyer {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a organizationPlanBuyer and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrganizationPlanBuyerTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.OrganizationPlanBuyer {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple organizationPlanBuyers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrganizationPlanBuyerTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrganizationPlanBuyerSlice, error) {
	var err error
	m := make(models.OrganizationPlanBuyerSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple organizationPlanBuyers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrganizationPlanBuyerTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrganizationPlanBuyerSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple organizationPlanBuyers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrganizationPlanBuyerTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrganizationPlanBuyerSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// OrganizationPlanBuyer has methods that act as mods for the OrganizationPlanBuyerTemplate
var OrganizationPlanBuyerMods organizationPlanBuyerMods

type organizationPlanBuyerMods struct{}

func (m organizationPlanBuyerMods) RandomizeAllColumns(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModSlice{
		OrganizationPlanBuyerMods.RandomID(f),
		OrganizationPlanBuyerMods.RandomCompanyName(f),
		OrganizationPlanBuyerMods.RandomPhoneNumber(f),
		OrganizationPlanBuyerMods.RandomEmail(f),
		OrganizationPlanBuyerMods.RandomRepresentative(f),
		OrganizationPlanBuyerMods.RandomUserName(f),
		OrganizationPlanBuyerMods.RandomPostcode(f),
		OrganizationPlanBuyerMods.RandomAddress1(f),
		OrganizationPlanBuyerMods.RandomAddress2(f),
		OrganizationPlanBuyerMods.RandomInvoicePostcode(f),
		OrganizationPlanBuyerMods.RandomInvoiceAddress1(f),
		OrganizationPlanBuyerMods.RandomInvoiceAddress2(f),
		OrganizationPlanBuyerMods.RandomInvoiceUserName(f),
		OrganizationPlanBuyerMods.RandomInvoiceEmail(f),
		OrganizationPlanBuyerMods.RandomCreatedAt(f),
		OrganizationPlanBuyerMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) ID(val int32) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) IDFunc(f func() int32) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetID() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomID(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) CompanyName(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CompanyName = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) CompanyNameFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CompanyName = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetCompanyName() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CompanyName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomCompanyName(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CompanyName = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) PhoneNumber(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.PhoneNumber = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) PhoneNumberFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.PhoneNumber = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetPhoneNumber() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.PhoneNumber = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomPhoneNumber(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.PhoneNumber = func() string {
			return random_string(f, "128")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) Email(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) EmailFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetEmail() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomEmail(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Email = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) Representative(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Representative = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) RepresentativeFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Representative = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetRepresentative() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Representative = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomRepresentative(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Representative = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) UserName(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UserName = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) UserNameFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UserName = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetUserName() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UserName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomUserName(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UserName = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) Postcode(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Postcode = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) PostcodeFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Postcode = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetPostcode() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Postcode = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomPostcode(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Postcode = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) Address1(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address1 = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) Address1Func(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address1 = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetAddress1() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address1 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomAddress1(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address1 = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) Address2(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address2 = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) Address2Func(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address2 = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetAddress2() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address2 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomAddress2(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.Address2 = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) InvoicePostcode(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoicePostcode = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) InvoicePostcodeFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoicePostcode = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetInvoicePostcode() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoicePostcode = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomInvoicePostcode(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoicePostcode = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) InvoiceAddress1(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress1 = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) InvoiceAddress1Func(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress1 = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetInvoiceAddress1() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress1 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomInvoiceAddress1(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress1 = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) InvoiceAddress2(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress2 = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) InvoiceAddress2Func(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress2 = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetInvoiceAddress2() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress2 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomInvoiceAddress2(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceAddress2 = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) InvoiceUserName(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceUserName = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) InvoiceUserNameFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceUserName = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetInvoiceUserName() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceUserName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomInvoiceUserName(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceUserName = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) InvoiceEmail(val string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceEmail = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) InvoiceEmailFunc(f func() string) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceEmail = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetInvoiceEmail() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceEmail = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomInvoiceEmail(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.InvoiceEmail = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) CreatedAt(val time.Time) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) CreatedAtFunc(f func() time.Time) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetCreatedAt() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomCreatedAt(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

// Set the model columns to this value
func (m organizationPlanBuyerMods) UpdatedAt(val time.Time) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationPlanBuyerMods) UpdatedAtFunc(f func() time.Time) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m organizationPlanBuyerMods) UnsetUpdatedAt() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPlanBuyerMods) RandomUpdatedAt(f *faker.Faker) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(_ context.Context, o *OrganizationPlanBuyerTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f, "6")
		}
	})
}

func (m organizationPlanBuyerMods) WithParentsCascading() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(ctx context.Context, o *OrganizationPlanBuyerTemplate) {
		if isDone, _ := organizationPlanBuyerWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = organizationPlanBuyerWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m organizationPlanBuyerMods) WithOrganizationPlans(number int, related *OrganizationPlanTemplate) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(ctx context.Context, o *OrganizationPlanBuyerTemplate) {
		o.r.OrganizationPlans = []*organizationPlanBuyerROrganizationPlansR{{
			number: number,
			o:      related,
		}}
	})
}

func (m organizationPlanBuyerMods) WithNewOrganizationPlans(number int, mods ...OrganizationPlanMod) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(ctx context.Context, o *OrganizationPlanBuyerTemplate) {
		related := o.f.NewOrganizationPlanWithContext(ctx, mods...)
		m.WithOrganizationPlans(number, related).Apply(ctx, o)
	})
}

func (m organizationPlanBuyerMods) AddOrganizationPlans(number int, related *OrganizationPlanTemplate) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(ctx context.Context, o *OrganizationPlanBuyerTemplate) {
		o.r.OrganizationPlans = append(o.r.OrganizationPlans, &organizationPlanBuyerROrganizationPlansR{
			number: number,
			o:      related,
		})
	})
}

func (m organizationPlanBuyerMods) AddNewOrganizationPlans(number int, mods ...OrganizationPlanMod) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(ctx context.Context, o *OrganizationPlanBuyerTemplate) {
		related := o.f.NewOrganizationPlanWithContext(ctx, mods...)
		m.AddOrganizationPlans(number, related).Apply(ctx, o)
	})
}

func (m organizationPlanBuyerMods) AddExistingOrganizationPlans(existingModels ...*models.OrganizationPlan) OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(ctx context.Context, o *OrganizationPlanBuyerTemplate) {
		for _, em := range existingModels {
			o.r.OrganizationPlans = append(o.r.OrganizationPlans, &organizationPlanBuyerROrganizationPlansR{
				o: o.f.FromExistingOrganizationPlan(em),
			})
		}
	})
}

func (m organizationPlanBuyerMods) WithoutOrganizationPlans() OrganizationPlanBuyerMod {
	return OrganizationPlanBuyerModFunc(func(ctx context.Context, o *OrganizationPlanBuyerTemplate) {
		o.r.OrganizationPlans = nil
	})
}
