// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var BannerErrors = &bannerErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "banners",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type bannerErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
