// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var OrganizationErrors = &organizationErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "organizations",
		columns: []string{"id"},
		s:       "PRIMARY",
	},

	ErrUniqueUkOrganizationsIdentifier: &UniqueConstraintError{
		schema:  "",
		table:   "organizations",
		columns: []string{"identifier"},
		s:       "uk_organizations_identifier",
	},
}

type organizationErrors struct {
	ErrUniquePrimary *UniqueConstraintError

	ErrUniqueUkOrganizationsIdentifier *UniqueConstraintError
}
