// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var OrganizationPlanErrors = &organizationPlanErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "organization_plans",
		columns: []string{"id"},
		s:       "PRIMARY",
	},

	ErrUniqueUkOrganizationPlanOrganizationIdIsEnabled: &UniqueConstraintError{
		schema:  "",
		table:   "organization_plans",
		columns: []string{"organization_id", "is_enabled"},
		s:       "uk_organization_plan_organization_id_is_enabled",
	},
}

type organizationPlanErrors struct {
	ErrUniquePrimary *UniqueConstraintError

	ErrUniqueUkOrganizationPlanOrganizationIdIsEnabled *UniqueConstraintError
}
