// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var OrganizationPlanBuyerErrors = &organizationPlanBuyerErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "organization_plan_buyers",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type organizationPlanBuyerErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
